const TOURS_DATA = [
  // ===================== TAIWAN 台灣 (33 tours) =====================
  // 1日遊 ×3
  {
    key: 'tw_taipei1day',
    region: 'taiwan',
    days: 1,
    name: '台北故宮＋淡水老街',
    emoji: '🏛️',
    c1: '#fde68a',
    c2: '#fb923c',
    price: 1980,
    meta: '台北市・小團12人・♿無障礙',
    tags: 'taiwan easy accessible',
    tip: '一日遊',
    tipClass: 'b-orange',
    b1: '♿ 無障礙',
    b1c: 'b-green',
    b2: '🌅 一日輕鬆',
    b2c: 'b-orange',
    b3: '🚌 全程專車',
    b3c: 'b-blue'
  },
  {
    key: 'tw_taichung1day',
    region: 'taiwan',
    days: 1,
    name: '台中彩虹眷村＋逢甲夜市',
    emoji: '🎨',
    c1: '#fbbf24',
    c2: '#f472b6',
    price: 1880,
    meta: '台中市・小團12人・♿無障礙',
    tags: 'taiwan easy accessible',
    tip: '一日遊',
    tipClass: 'b-orange',
    b1: '♿ 無障礙',
    b1c: 'b-green',
    b2: '🌅 一日輕鬆',
    b2c: 'b-orange',
    b3: '🚌 全程專車',
    b3c: 'b-blue'
  },
  {
    key: 'tw_kaohsiung1day',
    region: 'taiwan',
    days: 1,
    name: '高雄蓮池潭＋駁二藝術特區',
    emoji: '🪷',
    c1: '#86efac',
    c2: '#22d3ee',
    price: 1880,
    meta: '高雄市・小團12人・♿無障礙',
    tags: 'taiwan easy accessible',
    tip: '一日遊',
    tipClass: 'b-orange',
    b1: '♿ 無障礙',
    b1c: 'b-green',
    b2: '🌅 一日輕鬆',
    b2c: 'b-orange',
    b3: '🚌 全程專車',
    b3c: 'b-blue'
  },
  // 2天 ×3
  {
    key: 'tw_yilan2d',
    region: 'taiwan',
    days: 2,
    name: '宜蘭溫泉礁溪養生 2天1夜',
    emoji: '♨️',
    c1: '#6ee7b7',
    c2: '#3b82f6',
    price: 5800,
    meta: '宜蘭礁溪・小團12人・♿無障礙',
    tags: 'taiwan easy accessible',
    tip: '泡湯首選',
    tipClass: 'b-teal',
    b1: '♿ 無障礙',
    b1c: 'b-green',
    b2: '♨️ 溫泉養生',
    b2c: 'b-teal',
    b3: '🍚 銀髮餐',
    b3c: 'b-green'
  },
  {
    key: 'tw_kenting2d',
    region: 'taiwan',
    days: 2,
    name: '墾丁南灣海景悠閒 2天1夜',
    emoji: '🌊',
    c1: '#34d399',
    c2: '#facc15',
    price: 5980,
    meta: '屏東墾丁・小團12人・♿無障礙',
    tags: 'taiwan easy accessible',
    tip: '海景首選',
    tipClass: 'b-teal',
    b1: '♿ 無障礙',
    b1c: 'b-green',
    b2: '🌊 海景療癒',
    b2c: 'b-teal',
    b3: '🚌 全程專車',
    b3c: 'b-blue'
  },
  {
    key: 'tw_beitou2d',
    region: 'taiwan',
    days: 2,
    name: '北投溫泉文化館養生 2天1夜',
    emoji: '♨️',
    c1: '#a5f3fc',
    c2: '#818cf8',
    price: 5600,
    meta: '台北北投・小團10人・♿無障礙',
    tags: 'taiwan easy accessible',
    tip: '療癒之旅',
    tipClass: 'b-teal',
    b1: '♿ 無障礙',
    b1c: 'b-green',
    b2: '♨️ 溫泉放鬆',
    b2c: 'b-teal',
    b3: '🏥 醫療保障',
    b3c: 'b-blue'
  },
  // 3天 ×3
  {
    key: 'tw_taichung3d',
    region: 'taiwan',
    days: 3,
    name: '台中日月潭清境農場 3天2夜',
    emoji: '🌄',
    c1: '#fde68a',
    c2: '#4ade80',
    price: 8800,
    meta: '台中・南投・小團12人・♿無障礙',
    tags: 'taiwan easy accessible',
    tip: '山水之美',
    tipClass: 'b-green',
    b1: '♿ 無障礙',
    b1c: 'b-green',
    b2: '🌄 山景療癒',
    b2c: 'b-green',
    b3: '🚌 全程專車',
    b3c: 'b-blue'
  },
  {
    key: 'tw_tainan3d',
    region: 'taiwan',
    days: 3,
    name: '台南古蹟美食文化 3天2夜',
    emoji: '🏯',
    c1: '#fbbf24',
    c2: '#f97316',
    price: 8500,
    meta: '台南市・小團12人・♿無障礙',
    tags: 'taiwan easy accessible',
    tip: '文化饗宴',
    tipClass: 'b-orange',
    b1: '♿ 無障礙',
    b1c: 'b-green',
    b2: '🍜 在地美食',
    b2c: 'b-orange',
    b3: '🚌 全程專車',
    b3c: 'b-blue'
  },
  {
    key: 'tw_penghu3d',
    region: 'taiwan',
    days: 3,
    name: '澎湖藍海玄武岩 3天2夜',
    emoji: '🏝️',
    c1: '#38bdf8',
    c2: '#34d399',
    price: 9800,
    meta: '澎湖群島・小團10人・♿無障礙',
    tags: 'taiwan easy accessible',
    tip: '離島探秘',
    tipClass: 'b-teal',
    b1: '♿ 無障礙',
    b1c: 'b-green',
    b2: '🌊 海島慢遊',
    b2c: 'b-teal',
    b3: '🍚 海鮮美食',
    b3c: 'b-orange'
  },
  // 4天 ×3
  {
    key: 'tw_hualien4d',
    region: 'taiwan',
    days: 4,
    name: '花蓮太魯閣峽谷縱走 4天3夜',
    emoji: '🏔️',
    c1: '#67e8f9',
    c2: '#818cf8',
    price: 12800,
    meta: '花蓮縣・小團10人・♿無障礙',
    tags: 'taiwan accessible',
    tip: '峽谷奇景',
    tipClass: 'b-blue',
    b1: '♿ 無障礙',
    b1c: 'b-green',
    b2: '🏔️ 山水奇景',
    b2c: 'b-blue',
    b3: '🚌 全程專車',
    b3c: 'b-blue'
  },
  {
    key: 'tw_taitung4d',
    region: 'taiwan',
    days: 4,
    name: '台東池上綠野縱谷慢活 4天3夜',
    emoji: '🌾',
    c1: '#86efac',
    c2: '#fbbf24',
    price: 12500,
    meta: '台東縣・小團12人・♿無障礙',
    tags: 'taiwan easy accessible',
    tip: '縱谷慢活',
    tipClass: 'b-green',
    b1: '♿ 無障礙',
    b1c: 'b-green',
    b2: '🌾 田園風光',
    b2c: 'b-green',
    b3: '🍚 有機飲食',
    b3c: 'b-teal'
  },
  {
    key: 'tw_kinmen4d',
    region: 'taiwan',
    days: 4,
    name: '金門戰地歷史文化 4天3夜',
    emoji: '🏰',
    c1: '#fca5a5',
    c2: '#fbbf24',
    price: 13200,
    meta: '金門縣・小團12人・♿無障礙',
    tags: 'taiwan easy accessible',
    tip: '歷史之旅',
    tipClass: 'b-orange',
    b1: '♿ 無障礙',
    b1c: 'b-green',
    b2: '🏰 戰地文化',
    b2c: 'b-orange',
    b3: '🚌 全程專車',
    b3c: 'b-blue'
  },
  // 5天 ×3
  {
    key: 'tw_tainan5d',
    region: 'taiwan',
    days: 5,
    name: '台南嘉義府城深度文化 5天4夜',
    emoji: '🎋',
    c1: '#fde68a',
    c2: '#86efac',
    price: 15800,
    meta: '台南・嘉義・小團12人・♿無障礙',
    tags: 'taiwan easy accessible',
    tip: '文化深度',
    tipClass: 'b-purple',
    b1: '♿ 無障礙',
    b1c: 'b-green',
    b2: '🎋 深度文化',
    b2c: 'b-purple',
    b3: '🍜 古早味美食',
    b3c: 'b-orange'
  },
  {
    key: 'tw_northcoast5d',
    region: 'taiwan',
    days: 5,
    name: '北海岸野柳基隆海岸線 5天4夜',
    emoji: '🌊',
    c1: '#38bdf8',
    c2: '#6366f1',
    price: 14800,
    meta: '新北・基隆・小團12人・♿無障礙',
    tags: 'taiwan easy accessible',
    tip: '海岸秘境',
    tipClass: 'b-teal',
    b1: '♿ 無障礙',
    b1c: 'b-green',
    b2: '🌊 海岸風光',
    b2c: 'b-teal',
    b3: '🚌 全程專車',
    b3c: 'b-blue'
  },
  {
    key: 'tw_penghu5d',
    region: 'taiwan',
    days: 5,
    name: '澎湖七美望安秘境 5天4夜',
    emoji: '🏝️',
    c1: '#22d3ee',
    c2: '#4ade80',
    price: 16800,
    meta: '澎湖群島・小團10人・♿無障礙',
    tags: 'taiwan easy accessible',
    tip: '離島天堂',
    tipClass: 'b-teal',
    b1: '♿ 無障礙',
    b1c: 'b-green',
    b2: '🏝️ 離島秘境',
    b2c: 'b-teal',
    b3: '🍚 海鮮盛宴',
    b3c: 'b-orange'
  },
  // 6天 ×3
  {
    key: 'tw_alishan6d',
    region: 'taiwan',
    days: 6,
    name: '阿里山日出神木森林 6天5夜',
    emoji: '🌲',
    c1: '#4ade80',
    c2: '#fbbf24',
    price: 19800,
    meta: '嘉義阿里山・小團10人・♿無障礙',
    tags: 'taiwan accessible',
    tip: '高山秘境',
    tipClass: 'b-green',
    b1: '♿ 無障礙',
    b1c: 'b-green',
    b2: '🌲 森林浴',
    b2c: 'b-green',
    b3: '🌅 雲海日出',
    b3c: 'b-orange'
  },
  {
    key: 'tw_eastcoast6d',
    region: 'taiwan',
    days: 6,
    name: '東海岸石梯坪秀姑巒溪 6天5夜',
    emoji: '🌊',
    c1: '#67e8f9',
    c2: '#34d399',
    price: 19500,
    meta: '花蓮・台東・小團12人・♿無障礙',
    tags: 'taiwan accessible',
    tip: '東岸秘境',
    tipClass: 'b-teal',
    b1: '♿ 無障礙',
    b1c: 'b-green',
    b2: '🌊 東岸風光',
    b2c: 'b-teal',
    b3: '🚌 全程專車',
    b3c: 'b-blue'
  },
  {
    key: 'tw_teakulture6d',
    region: 'taiwan',
    days: 6,
    name: '坪林梨山茶文化慢遊 6天5夜',
    emoji: '🍵',
    c1: '#86efac',
    c2: '#a78bfa',
    price: 18800,
    meta: '新北・台中梨山・小團12人・♿無障礙',
    tags: 'taiwan easy accessible',
    tip: '茶鄉慢活',
    tipClass: 'b-green',
    b1: '♿ 無障礙',
    b1c: 'b-green',
    b2: '🍵 茶文化體驗',
    b2c: 'b-green',
    b3: '🌿 養生之旅',
    b3c: 'b-teal'
  },
  // 7天 ×3
  {
    key: 'tw_west7d',
    region: 'taiwan',
    days: 7,
    name: '西部縱貫精華城市 7天6夜',
    emoji: '🏙️',
    c1: '#fbbf24',
    c2: '#f472b6',
    price: 22800,
    meta: '台北至高雄・小團12人・♿無障礙',
    tags: 'taiwan easy accessible',
    tip: '西岸精華',
    tipClass: 'b-orange',
    b1: '♿ 無障礙',
    b1c: 'b-green',
    b2: '🏙️ 城市文化',
    b2c: 'b-orange',
    b3: '🚌 全程專車',
    b3c: 'b-blue'
  },
  {
    key: 'tw_eastvalley7d',
    region: 'taiwan',
    days: 7,
    name: '東部縱谷花東健康療癒 7天6夜',
    emoji: '🌾',
    c1: '#86efac',
    c2: '#38bdf8',
    price: 23800,
    meta: '花蓮・台東縱谷・小團10人・♿無障礙',
    tags: 'taiwan easy accessible',
    tip: '縱谷療癒',
    tipClass: 'b-green',
    b1: '♿ 無障礙',
    b1c: 'b-green',
    b2: '🌾 縱谷風光',
    b2c: 'b-green',
    b3: '🏥 健康管理',
    b3c: 'b-blue'
  },
  {
    key: 'tw_foodmap7d',
    region: 'taiwan',
    days: 7,
    name: '台灣美食地圖環島饗宴 7天6夜',
    emoji: '🍜',
    c1: '#fca5a5',
    c2: '#fbbf24',
    price: 22500,
    meta: '全台美食・小團12人・♿無障礙',
    tags: 'taiwan easy accessible',
    tip: '美食探索',
    tipClass: 'b-orange',
    b1: '♿ 無障礙',
    b1c: 'b-green',
    b2: '🍜 在地美食',
    b2c: 'b-orange',
    b3: '🚌 全程專車',
    b3c: 'b-blue'
  },
  // 8天 ×3
  {
    key: 'taiwan',
    region: 'taiwan',
    days: 8,
    name: '台灣環島全覽 8天7夜',
    emoji: '🗺️',
    c1: '#f9a8d4',
    c2: '#818cf8',
    price: 29800,
    meta: '全台環島・小團12人・♿無障礙',
    tags: 'taiwan accessible',
    tip: '環島經典',
    tipClass: 'b-purple',
    b1: '♿ 無障礙',
    b1c: 'b-green',
    b2: '🗺️ 環島探索',
    b2c: 'b-purple',
    b3: '🚌 全程專車',
    b3c: 'b-blue'
  },
  {
    key: 'tw_east8d',
    region: 'taiwan',
    days: 8,
    name: '東台灣深度花東縱谷 8天7夜',
    emoji: '🏔️',
    c1: '#67e8f9',
    c2: '#4ade80',
    price: 27800,
    meta: '花蓮・台東・小團10人・♿無障礙',
    tags: 'taiwan accessible',
    tip: '東台灣秘境',
    tipClass: 'b-teal',
    b1: '♿ 無障礙',
    b1c: 'b-green',
    b2: '🏔️ 山海風光',
    b2c: 'b-teal',
    b3: '🌿 自然療癒',
    b3c: 'b-green'
  },
  {
    key: 'tw_natural8d',
    region: 'taiwan',
    days: 8,
    name: '台灣自然生態濕地秘境 8天7夜',
    emoji: '🦋',
    c1: '#86efac',
    c2: '#fbbf24',
    price: 26800,
    meta: '全台生態・小團10人・♿無障礙',
    tags: 'taiwan easy accessible',
    tip: '生態探秘',
    tipClass: 'b-green',
    b1: '♿ 無障礙',
    b1c: 'b-green',
    b2: '🦋 生態體驗',
    b2c: 'b-green',
    b3: '🌿 自然療癒',
    b3c: 'b-teal'
  },
  // 10天 ×3
  {
    key: 'tw_10d',
    region: 'taiwan',
    days: 10,
    name: '台灣精華全覽深度 10天9夜',
    emoji: '🌏',
    c1: '#a78bfa',
    c2: '#38bdf8',
    price: 35800,
    meta: '全台・小團12人・♿無障礙',
    tags: 'taiwan accessible',
    tip: '深度精選',
    tipClass: 'b-purple',
    b1: '♿ 無障礙',
    b1c: 'b-green',
    b2: '🌏 全台深度',
    b2c: 'b-purple',
    b3: '🚌 全程專車',
    b3c: 'b-blue'
  },
  {
    key: 'tw_health10d',
    region: 'taiwan',
    days: 10,
    name: '台灣健康養生溫泉療癒 10天9夜',
    emoji: '🌿',
    c1: '#4ade80',
    c2: '#a78bfa',
    price: 36500,
    meta: '全台溫泉・小團10人・♿無障礙',
    tags: 'taiwan easy accessible',
    tip: '養生首選',
    tipClass: 'b-green',
    b1: '♿ 無障礙',
    b1c: 'b-green',
    b2: '🌿 養生療癒',
    b2c: 'b-green',
    b3: '🏥 健康管理',
    b3c: 'b-blue'
  },
  {
    key: 'tw_culture10d',
    region: 'taiwan',
    days: 10,
    name: '台灣原住民文化藝術 10天9夜',
    emoji: '🎭',
    c1: '#fca5a5',
    c2: '#fbbf24',
    price: 34800,
    meta: '全台原鄉・小團10人・♿無障礙',
    tags: 'taiwan easy accessible',
    tip: '文化體驗',
    tipClass: 'b-orange',
    b1: '♿ 無障礙',
    b1c: 'b-green',
    b2: '🎭 原民文化',
    b2c: 'b-orange',
    b3: '🍚 原鄉美食',
    b3c: 'b-teal'
  },
  // 12天 ×3
  {
    key: 'tw_12d',
    region: 'taiwan',
    days: 12,
    name: '台灣南北縱橫全程 12天11夜',
    emoji: '🗺️',
    c1: '#818cf8',
    c2: '#f472b6',
    price: 42800,
    meta: '全台・小團12人・♿無障礙',
    tags: 'taiwan accessible',
    tip: '全台精選',
    tipClass: 'b-purple',
    b1: '♿ 無障礙',
    b1c: 'b-green',
    b2: '🗺️ 南北縱橫',
    b2c: 'b-purple',
    b3: '🚌 全程專車',
    b3c: 'b-blue'
  },
  {
    key: 'tw_island12d',
    region: 'taiwan',
    days: 12,
    name: '台灣四大離島逐夢 12天11夜',
    emoji: '🏝️',
    c1: '#22d3ee',
    c2: '#818cf8',
    price: 48800,
    meta: '金門・馬祖・澎湖・綠島・小團10人',
    tags: 'taiwan accessible',
    tip: '離島探秘',
    tipClass: 'b-teal',
    b1: '♿ 無障礙',
    b1c: 'b-green',
    b2: '🏝️ 四島巡禮',
    b2c: 'b-teal',
    b3: '✈️ 含島內機票',
    b3c: 'b-blue'
  },
  {
    key: 'tw_mountain12d',
    region: 'taiwan',
    days: 12,
    name: '台灣百岳周邊高山慢遊 12天11夜',
    emoji: '⛰️',
    c1: '#86efac',
    c2: '#6366f1',
    price: 44800,
    meta: '全台山區・小團10人・♿無障礙',
    tags: 'taiwan accessible',
    tip: '山岳精選',
    tipClass: 'b-blue',
    b1: '♿ 無障礙',
    b1c: 'b-green',
    b2: '⛰️ 高山探秘',
    b2c: 'b-blue',
    b3: '🌿 森林浴',
    b3c: 'b-green'
  },
  // 15天 ×3
  {
    key: 'tw_15d',
    region: 'taiwan',
    days: 15,
    name: '台灣深度全覽慢旅 15天14夜',
    emoji: '🌏',
    c1: '#f9a8d4',
    c2: '#818cf8',
    price: 56800,
    meta: '全台・小團12人・♿無障礙',
    tags: 'taiwan accessible',
    tip: '最完整',
    tipClass: 'b-purple',
    b1: '♿ 無障礙',
    b1c: 'b-green',
    b2: '🌏 深度全覽',
    b2c: 'b-purple',
    b3: '🚌 全程專車',
    b3c: 'b-blue'
  },
  {
    key: 'tw_wellness15d',
    region: 'taiwan',
    days: 15,
    name: '台灣銀髮健康慢活養生 15天14夜',
    emoji: '🧘',
    c1: '#4ade80',
    c2: '#fbbf24',
    price: 58800,
    meta: '全台養生・小團10人・♿無障礙',
    tags: 'taiwan easy accessible',
    tip: '養生療癒',
    tipClass: 'b-green',
    b1: '♿ 無障礙',
    b1c: 'b-green',
    b2: '🧘 身心療癒',
    b2c: 'b-green',
    b3: '🏥 醫療保障',
    b3c: 'b-blue'
  },
  {
    key: 'tw_heritage15d',
    region: 'taiwan',
    days: 15,
    name: '台灣世界遺產潛力點巡禮 15天14夜',
    emoji: '🏛️',
    c1: '#fbbf24',
    c2: '#a78bfa',
    price: 55800,
    meta: '全台文化遺址・小團10人・♿無障礙',
    tags: 'taiwan accessible',
    tip: '文化遺產',
    tipClass: 'b-purple',
    b1: '♿ 無障礙',
    b1c: 'b-green',
    b2: '🏛️ 遺產探索',
    b2c: 'b-purple',
    b3: '🎭 文化饗宴',
    b3c: 'b-orange'
  },

  // ===================== JAPAN 日本 (33 tours) =====================
  // 3天 ×3
  {
    key: 'jp_tokyo3d',
    region: 'japan',
    days: 3,
    name: '東京淺草秋葉原銀座 3天2夜',
    emoji: '🗼',
    c1: '#fca5a5',
    c2: '#f472b6',
    price: 38800,
    meta: '日本東京・小團10人・♿無障礙',
    tags: 'japan easy accessible',
    tip: '東京精選',
    tipClass: 'b-orange',
    b1: '♿ 無障礙',
    b1c: 'b-green',
    b2: '🗼 城市文化',
    b2c: 'b-orange',
    b3: '🚌 全程專車',
    b3c: 'b-blue'
  },
  {
    key: 'jp_tokyo3d_b',
    region: 'japan',
    days: 3,
    name: '東京上野新宿日本橋 3天2夜',
    emoji: '🌸',
    c1: '#fbcfe8',
    c2: '#fbbf24',
    price: 39800,
    meta: '日本東京・小團10人・♿無障礙',
    tags: 'japan easy accessible',
    tip: '樂齡首選',
    tipClass: 'b-green',
    b1: '♿ 無障礙',
    b1c: 'b-green',
    b2: '🌸 春季賞花',
    b2c: 'b-green',
    b3: '🍱 頂級料理',
    b3c: 'b-orange'
  },
  {
    key: 'jp_tokyo3d_c',
    region: 'japan',
    days: 3,
    name: '東京迪士尼溫泉精選 3天2夜',
    emoji: '🎡',
    c1: '#fde68a',
    c2: '#f472b6',
    price: 41800,
    meta: '日本東京・小團12人・♿無障礙',
    tags: 'japan easy accessible',
    tip: '歡樂之旅',
    tipClass: 'b-orange',
    b1: '♿ 無障礙',
    b1c: 'b-green',
    b2: '🎡 歡樂體驗',
    b2c: 'b-orange',
    b3: '♨️ 溫泉放鬆',
    b3c: 'b-teal'
  },
  // 4天 ×3
  {
    key: 'jp_osaka4d',
    region: 'japan',
    days: 4,
    name: '大阪京都奈良關西漫步 4天3夜',
    emoji: '🏯',
    c1: '#fbbf24',
    c2: '#f97316',
    price: 44800,
    meta: '日本關西・小團10人・♿無障礙',
    tags: 'japan easy accessible',
    tip: '關西精選',
    tipClass: 'b-orange',
    b1: '♿ 無障礙',
    b1c: 'b-green',
    b2: '🏯 古都文化',
    b2c: 'b-orange',
    b3: '🍱 大阪美食',
    b3c: 'b-orange'
  },
  {
    key: 'jp_osaka4d_b',
    region: 'japan',
    days: 4,
    name: '大阪神戶淡路島海景 4天3夜',
    emoji: '🌊',
    c1: '#38bdf8',
    c2: '#4ade80',
    price: 43800,
    meta: '日本關西・小團10人・♿無障礙',
    tags: 'japan easy accessible',
    tip: '海景療癒',
    tipClass: 'b-teal',
    b1: '♿ 無障礙',
    b1c: 'b-green',
    b2: '🌊 海景漫步',
    b2c: 'b-teal',
    b3: '🍱 神戶牛排',
    b3c: 'b-orange'
  },
  {
    key: 'jp_osaka4d_c',
    region: 'japan',
    days: 4,
    name: '大阪名古屋東海道 4天3夜',
    emoji: '🏙️',
    c1: '#fca5a5',
    c2: '#818cf8',
    price: 45800,
    meta: '日本東海・小團12人・♿無障礙',
    tags: 'japan easy accessible',
    tip: '東海精選',
    tipClass: 'b-blue',
    b1: '♿ 無障礙',
    b1c: 'b-green',
    b2: '🏙️ 城市探索',
    b2c: 'b-blue',
    b3: '🚌 全程專車',
    b3c: 'b-blue'
  },
  // 5天 ×3
  {
    key: 'kyoto',
    region: 'japan',
    days: 5,
    name: '京都賞櫻溫泉 5天4夜',
    emoji: '🌸',
    c1: '#fbbf24',
    c2: '#f97316',
    price: 48800,
    meta: '日本關西・小團10人・♿無障礙',
    tags: 'japan accessible easy',
    tip: '朋友推薦',
    tipClass: 'b-green',
    b1: '♿ 無障礙',
    b1c: 'b-green',
    b2: '🚶 緩步行',
    b2c: 'b-green',
    b3: '🏥 醫療',
    b3c: 'b-blue'
  },
  {
    key: 'jp_okinawa5d',
    region: 'japan',
    days: 5,
    name: '沖繩海島療癒度假 5天4夜',
    emoji: '🏖️',
    c1: '#22d3ee',
    c2: '#4ade80',
    price: 46800,
    meta: '日本沖繩・小團10人・♿無障礙',
    tags: 'japan accessible easy',
    tip: '海島首選',
    tipClass: 'b-teal',
    b1: '♿ 無障礙',
    b1c: 'b-green',
    b2: '🏖️ 海島療癒',
    b2c: 'b-teal',
    b3: '🍱 琉球料理',
    b3c: 'b-orange'
  },
  {
    key: 'jp_5d_c',
    region: 'japan',
    days: 5,
    name: '東京富士山箱根溫泉 5天4夜',
    emoji: '🗻',
    c1: '#a5f3fc',
    c2: '#818cf8',
    price: 49800,
    meta: '日本關東・小團10人・♿無障礙',
    tags: 'japan accessible easy',
    tip: '富士精選',
    tipClass: 'b-blue',
    b1: '♿ 無障礙',
    b1c: 'b-green',
    b2: '🗻 富士巡禮',
    b2c: 'b-blue',
    b3: '♨️ 箱根溫泉',
    b3c: 'b-teal'
  },
  // 6天 ×3
  {
    key: 'hokkaido',
    region: 'japan',
    days: 6,
    name: '北海道養生溫泉療癒 6天5夜',
    emoji: '🌿',
    c1: '#a78bfa',
    c2: '#ec4899',
    price: 56800,
    meta: '日本北海道・小團8人・♿無障礙',
    tags: 'japan accessible easy',
    tip: '最輕鬆',
    tipClass: 'b-green',
    b1: '♿ 無障礙',
    b1c: 'b-green',
    b2: '🍚 銀髮餐',
    b2c: 'b-green',
    b3: '🚶 最輕鬆',
    b3c: 'b-green'
  },
  {
    key: 'jp_6d_b',
    region: 'japan',
    days: 6,
    name: '京都奈良金澤富山 6天5夜',
    emoji: '🏯',
    c1: '#fde68a',
    c2: '#86efac',
    price: 54800,
    meta: '日本關西北陸・小團10人・♿無障礙',
    tags: 'japan accessible easy',
    tip: '北陸精選',
    tipClass: 'b-orange',
    b1: '♿ 無障礙',
    b1c: 'b-green',
    b2: '🏯 古都巡禮',
    b2c: 'b-orange',
    b3: '🍱 海鮮美食',
    b3c: 'b-orange'
  },
  {
    key: 'jp_6d_c',
    region: 'japan',
    days: 6,
    name: '東北仙台松島楓葉 6天5夜',
    emoji: '🍁',
    c1: '#fca5a5',
    c2: '#fbbf24',
    price: 53800,
    meta: '日本東北・小團10人・♿無障礙',
    tags: 'japan accessible easy',
    tip: '楓葉首選',
    tipClass: 'b-orange',
    b1: '♿ 無障礙',
    b1c: 'b-green',
    b2: '🍁 賞楓之旅',
    b2c: 'b-orange',
    b3: '♨️ 溫泉放鬆',
    b3c: 'b-teal'
  },
  // 7天 ×3
  {
    key: 'jp_hiroshima7d',
    region: 'japan',
    days: 7,
    name: '廣島宮島四國巡禮 7天6夜',
    emoji: '⛩️',
    c1: '#fbbf24',
    c2: '#818cf8',
    price: 58800,
    meta: '日本廣島・四國・小團10人・♿無障礙',
    tags: 'japan accessible',
    tip: '深度歷史',
    tipClass: 'b-purple',
    b1: '♿ 無障礙',
    b1c: 'b-green',
    b2: '⛩️ 神社巡禮',
    b2c: 'b-purple',
    b3: '🚌 全程專車',
    b3c: 'b-blue'
  },
  {
    key: 'kyushu',
    region: 'japan',
    days: 7,
    name: '九州溫泉美食全覽 7天6夜',
    emoji: '♨️',
    c1: '#fca5a5',
    c2: '#f97316',
    price: 59800,
    meta: '日本九州・小團10人・♿無障礙',
    tags: 'japan accessible easy',
    tip: '九州療癒',
    tipClass: 'b-teal',
    b1: '♿ 無障礙',
    b1c: 'b-green',
    b2: '♨️ 溫泉療癒',
    b2c: 'b-teal',
    b3: '🍱 九州美食',
    b3c: 'b-orange'
  },
  {
    key: 'jp_7d_c',
    region: 'japan',
    days: 7,
    name: '北海道函館小樽秘境 7天6夜',
    emoji: '❄️',
    c1: '#bfdbfe',
    c2: '#a78bfa',
    price: 62800,
    meta: '日本北海道・小團8人・♿無障礙',
    tags: 'japan accessible easy',
    tip: '北海道秘境',
    tipClass: 'b-blue',
    b1: '♿ 無障礙',
    b1c: 'b-green',
    b2: '❄️ 雪景療癒',
    b2c: 'b-blue',
    b3: '🍱 海鮮盛宴',
    b3c: 'b-orange'
  },
  // 8天 ×3
  {
    key: 'jp_golden8d',
    region: 'japan',
    days: 8,
    name: '日本黃金路線東京大阪 8天7夜',
    emoji: '🥇',
    c1: '#fde68a',
    c2: '#f97316',
    price: 68800,
    meta: '日本關東關西・小團10人・♿無障礙',
    tags: 'japan accessible easy',
    tip: '黃金路線',
    tipClass: 'b-orange',
    b1: '♿ 無障礙',
    b1c: 'b-green',
    b2: '🥇 精選路線',
    b2c: 'b-orange',
    b3: '🍱 頂級料理',
    b3c: 'b-orange'
  },
  {
    key: 'jp_8d_b',
    region: 'japan',
    days: 8,
    name: '日本山陰山陽古道慢行 8天7夜',
    emoji: '🏞️',
    c1: '#86efac',
    c2: '#6366f1',
    price: 65800,
    meta: '日本山陰山陽・小團10人・♿無障礙',
    tags: 'japan accessible',
    tip: '山道秘境',
    tipClass: 'b-purple',
    b1: '♿ 無障礙',
    b1c: 'b-green',
    b2: '🏞️ 古道探索',
    b2c: 'b-purple',
    b3: '♨️ 名湯療癒',
    b3c: 'b-teal'
  },
  {
    key: 'jp_8d_c',
    region: 'japan',
    days: 8,
    name: '九州全域溫泉文化深度 8天7夜',
    emoji: '🌋',
    c1: '#fca5a5',
    c2: '#a78bfa',
    price: 67800,
    meta: '日本九州全域・小團10人・♿無障礙',
    tags: 'japan accessible easy',
    tip: '深度九州',
    tipClass: 'b-purple',
    b1: '♿ 無障礙',
    b1c: 'b-green',
    b2: '🌋 火山奇景',
    b2c: 'b-purple',
    b3: '♨️ 別府溫泉',
    b3c: 'b-teal'
  },
  // 10天 ×3
  {
    key: 'jp_full10d',
    region: 'japan',
    days: 10,
    name: '日本全覽東西精選 10天9夜',
    emoji: '🗾',
    c1: '#818cf8',
    c2: '#f472b6',
    price: 78800,
    meta: '日本全境・小團10人・♿無障礙',
    tags: 'japan accessible',
    tip: '全境精選',
    tipClass: 'b-purple',
    b1: '♿ 無障礙',
    b1c: 'b-green',
    b2: '🗾 全境探索',
    b2c: 'b-purple',
    b3: '🏥 醫療保障',
    b3c: 'b-blue'
  },
  {
    key: 'jp_10d_b',
    region: 'japan',
    days: 10,
    name: '日本東北北海道雙主題 10天9夜',
    emoji: '🍁',
    c1: '#fbbf24',
    c2: '#4ade80',
    price: 79800,
    meta: '日本東北北海道・小團8人・♿無障礙',
    tags: 'japan accessible easy',
    tip: '秋冬首選',
    tipClass: 'b-orange',
    b1: '♿ 無障礙',
    b1c: 'b-green',
    b2: '🍁 楓雪雙享',
    b2c: 'b-orange',
    b3: '♨️ 溫泉療癒',
    b3c: 'b-teal'
  },
  {
    key: 'jp_10d_c',
    region: 'japan',
    days: 10,
    name: '日本四國遍路秘境慢旅 10天9夜',
    emoji: '⛩️',
    c1: '#a5f3fc',
    c2: '#fbbf24',
    price: 76800,
    meta: '日本四國・小團10人・♿無障礙',
    tags: 'japan accessible',
    tip: '靈修之旅',
    tipClass: 'b-teal',
    b1: '♿ 無障礙',
    b1c: 'b-green',
    b2: '⛩️ 遍路巡禮',
    b2c: 'b-teal',
    b3: '🌿 身心淨化',
    b3c: 'b-green'
  },
  // 12天 ×3
  {
    key: 'jp_12d_a',
    region: 'japan',
    days: 12,
    name: '日本南北縱走九州至北海道 12天11夜',
    emoji: '🗾',
    c1: '#f9a8d4',
    c2: '#818cf8',
    price: 98800,
    meta: '日本全境・小團8人・♿無障礙',
    tags: 'japan accessible',
    tip: '南北縱走',
    tipClass: 'b-purple',
    b1: '♿ 無障礙',
    b1c: 'b-green',
    b2: '🗾 南北縱走',
    b2c: 'b-purple',
    b3: '🏥 醫療保障',
    b3c: 'b-blue'
  },
  {
    key: 'jp_12d_b',
    region: 'japan',
    days: 12,
    name: '日本溫泉名湯巡禮 12天11夜',
    emoji: '♨️',
    c1: '#6ee7b7',
    c2: '#a78bfa',
    price: 96800,
    meta: '日本全境溫泉・小團8人・♿無障礙',
    tags: 'japan accessible easy',
    tip: '溫泉精選',
    tipClass: 'b-teal',
    b1: '♿ 無障礙',
    b1c: 'b-green',
    b2: '♨️ 名湯巡禮',
    b2c: 'b-teal',
    b3: '🍱 懷石料理',
    b3c: 'b-orange'
  },
  {
    key: 'jp_12d_c',
    region: 'japan',
    days: 12,
    name: '日本四季祭典文化之旅 12天11夜',
    emoji: '🎏',
    c1: '#fbbf24',
    c2: '#f472b6',
    price: 95800,
    meta: '日本全境・小團10人・♿無障礙',
    tags: 'japan accessible',
    tip: '祭典體驗',
    tipClass: 'b-orange',
    b1: '♿ 無障礙',
    b1c: 'b-green',
    b2: '🎏 祭典文化',
    b2c: 'b-orange',
    b3: '🍱 季節料理',
    b3c: 'b-orange'
  },
  // 15天 ×3
  {
    key: 'jp_15d_a',
    region: 'japan',
    days: 15,
    name: '日本深度慢旅全境 15天14夜',
    emoji: '🗾',
    c1: '#818cf8',
    c2: '#ec4899',
    price: 128000,
    meta: '日本全境・小團8人・♿無障礙',
    tags: 'japan accessible',
    tip: '深度全境',
    tipClass: 'b-purple',
    b1: '♿ 無障礙',
    b1c: 'b-green',
    b2: '🗾 全境深度',
    b2c: 'b-purple',
    b3: '🏥 醫療保障',
    b3c: 'b-blue'
  },
  {
    key: 'jp_15d_b',
    region: 'japan',
    days: 15,
    name: '日本古道文化遺產精選 15天14夜',
    emoji: '🏛️',
    c1: '#fde68a',
    c2: '#818cf8',
    price: 125000,
    meta: '日本全境古道・小團8人・♿無障礙',
    tags: 'japan accessible',
    tip: '文化遺產',
    tipClass: 'b-purple',
    b1: '♿ 無障礙',
    b1c: 'b-green',
    b2: '🏛️ 文化遺產',
    b2c: 'b-purple',
    b3: '🌸 四季風情',
    b3c: 'b-green'
  },
  {
    key: 'jp_15d_c',
    region: 'japan',
    days: 15,
    name: '日本銀髮健康溫泉療養 15天14夜',
    emoji: '🌿',
    c1: '#4ade80',
    c2: '#38bdf8',
    price: 122000,
    meta: '日本溫泉勝地・小團8人・♿無障礙',
    tags: 'japan accessible easy',
    tip: '療養首選',
    tipClass: 'b-green',
    b1: '♿ 無障礙',
    b1c: 'b-green',
    b2: '🌿 健康療養',
    b2c: 'b-green',
    b3: '🏥 醫療保障',
    b3c: 'b-blue'
  },

  // Japan 2天 ×3
  {
    key: 'jp_2d_a',
    region: 'japan',
    days: 2,
    name: '大阪神戶短程美食輕旅 2天1夜',
    emoji: '🍜',
    c1: '#fde68a',
    c2: '#f97316',
    price: 28800,
    meta: '日本關西・小團12人・♿無障礙',
    tags: 'japan easy accessible',
    tip: '輕鬆短遊',
    tipClass: 'b-orange',
    b1: '♿ 無障礙',
    b1c: 'b-green',
    b2: '🍜 大阪美食',
    b2c: 'b-orange',
    b3: '🚌 全程專車',
    b3c: 'b-blue'
  },
  {
    key: 'jp_2d_b',
    region: 'japan',
    days: 2,
    name: '東京輕井澤高原清新 2天1夜',
    emoji: '🌿',
    c1: '#86efac',
    c2: '#38bdf8',
    price: 29800,
    meta: '日本關東・小團12人・♿無障礙',
    tags: 'japan easy accessible',
    tip: '高原清涼',
    tipClass: 'b-teal',
    b1: '♿ 無障礙',
    b1c: 'b-green',
    b2: '🌿 高原療癒',
    b2c: 'b-teal',
    b3: '♨️ 溫泉放鬆',
    b3c: 'b-teal'
  },
  {
    key: 'jp_2d_c',
    region: 'japan',
    days: 2,
    name: '京都一泊古寺禪意之旅 2天1夜',
    emoji: '⛩️',
    c1: '#fbbf24',
    c2: '#a78bfa',
    price: 31800,
    meta: '日本京都・小團10人・♿無障礙',
    tags: 'japan easy accessible',
    tip: '京都禪意',
    tipClass: 'b-purple',
    b1: '♿ 無障礙',
    b1c: 'b-green',
    b2: '⛩️ 禪寺文化',
    b2c: 'b-purple',
    b3: '🍱 精進料理',
    b3c: 'b-orange'
  },
  // Japan 14天 ×3
  {
    key: 'jp_14d_a',
    region: 'japan',
    days: 14,
    name: '日本縱貫本州四國九州 14天13夜',
    emoji: '🗾',
    c1: '#fca5a5',
    c2: '#818cf8',
    price: 118000,
    meta: '日本全境・小團8人・♿無障礙',
    tags: 'japan accessible',
    tip: '縱貫精選',
    tipClass: 'b-purple',
    b1: '♿ 無障礙',
    b1c: 'b-green',
    b2: '🗾 縱貫壯遊',
    b2c: 'b-purple',
    b3: '🏥 醫療保障',
    b3c: 'b-blue'
  },
  {
    key: 'jp_14d_b',
    region: 'japan',
    days: 14,
    name: '日本鐵道之旅四季風情 14天13夜',
    emoji: '🚂',
    c1: '#38bdf8',
    c2: '#fbbf24',
    price: 115000,
    meta: '日本全境鐵道・小團8人・♿無障礙',
    tags: 'japan accessible easy',
    tip: '鐵道慢旅',
    tipClass: 'b-blue',
    b1: '♿ 無障礙',
    b1c: 'b-green',
    b2: '🚂 鐵道慢遊',
    b2c: 'b-blue',
    b3: '♨️ 名湯巡禮',
    b3c: 'b-teal'
  },
  {
    key: 'jp_14d_c',
    region: 'japan',
    days: 14,
    name: '日本溫泉文化藝術精選 14天13夜',
    emoji: '🎎',
    c1: '#f9a8d4',
    c2: '#a78bfa',
    price: 112000,
    meta: '日本全境・小團8人・♿無障礙',
    tags: 'japan accessible',
    tip: '文化藝術',
    tipClass: 'b-purple',
    b1: '♿ 無障礙',
    b1c: 'b-green',
    b2: '🎎 藝術文化',
    b2c: 'b-purple',
    b3: '♨️ 溫泉療癒',
    b3c: 'b-teal'
  },

  // ===================== EUROPE 歐洲 (33 tours) =====================
  // 歐洲 5天 ×3
  {
    key: 'eu_5d_a',
    region: 'europe',
    days: 5,
    name: '法國巴黎週邊凡爾賽 5天4夜',
    emoji: '🗼',
    c1: '#c4b5fd',
    c2: '#fbbf24',
    price: 82000,
    meta: '法國巴黎・小團12人・♿無障礙',
    tags: 'europe easy accessible',
    tip: '巴黎精選',
    tipClass: 'b-purple',
    b1: '♿ 無障礙',
    b1c: 'b-green',
    b2: '🗼 巴黎初探',
    b2c: 'b-purple',
    b3: '🍷 法式料理',
    b3c: 'b-orange'
  },
  {
    key: 'eu_5d_b',
    region: 'europe',
    days: 5,
    name: '義大利羅馬梵蒂岡古蹟 5天4夜',
    emoji: '🏛️',
    c1: '#fde68a',
    c2: '#f97316',
    price: 80000,
    meta: '義大利羅馬・小團12人・♿無障礙',
    tags: 'europe easy accessible',
    tip: '永恆之城',
    tipClass: 'b-orange',
    b1: '♿ 無障礙',
    b1c: 'b-green',
    b2: '🏛️ 古蹟巡禮',
    b2c: 'b-orange',
    b3: '🍝 義式料理',
    b3c: 'b-orange'
  },
  {
    key: 'eu_5d_c',
    region: 'europe',
    days: 5,
    name: '西班牙巴塞隆納高第建築 5天4夜',
    emoji: '🎨',
    c1: '#fca5a5',
    c2: '#fbbf24',
    price: 83000,
    meta: '西班牙・小團12人・♿無障礙',
    tags: 'europe easy accessible',
    tip: '建築藝術',
    tipClass: 'b-orange',
    b1: '♿ 無障礙',
    b1c: 'b-green',
    b2: '🎨 建築藝術',
    b2c: 'b-orange',
    b3: '🍷 美酒美食',
    b3c: 'b-orange'
  },
  // 歐洲 6天 ×3
  {
    key: 'eu_6d_a',
    region: 'europe',
    days: 6,
    name: '瑞士日內瓦琉森蘇黎世 6天5夜',
    emoji: '🏔️',
    c1: '#bfdbfe',
    c2: '#f9a8d4',
    price: 98000,
    meta: '瑞士・小團10人・♿無障礙',
    tags: 'europe accessible easy',
    tip: '湖光山色',
    tipClass: 'b-blue',
    b1: '♿ 無障礙',
    b1c: 'b-green',
    b2: '🏔️ 阿爾卑斯',
    b2c: 'b-blue',
    b3: '🍫 瑞士美食',
    b3c: 'b-orange'
  },
  {
    key: 'eu_6d_b',
    region: 'europe',
    days: 6,
    name: '捷克布拉格維也納音樂之旅 6天5夜',
    emoji: '🎵',
    c1: '#a78bfa',
    c2: '#fbbf24',
    price: 92000,
    meta: '捷克・奧地利・小團12人・♿無障礙',
    tags: 'europe easy accessible',
    tip: '音樂之都',
    tipClass: 'b-purple',
    b1: '♿ 無障礙',
    b1c: 'b-green',
    b2: '🎵 音樂文化',
    b2c: 'b-purple',
    b3: '🏰 巴洛克建築',
    b3c: 'b-blue'
  },
  {
    key: 'eu_6d_c',
    region: 'europe',
    days: 6,
    name: '希臘雅典聖托里尼 6天5夜',
    emoji: '🌊',
    c1: '#38bdf8',
    c2: '#fbbf24',
    price: 95000,
    meta: '希臘・小團10人・♿無障礙',
    tags: 'europe easy accessible',
    tip: '藍白之美',
    tipClass: 'b-teal',
    b1: '♿ 無障礙',
    b1c: 'b-green',
    b2: '🌊 愛琴海藍',
    b2c: 'b-teal',
    b3: '🍷 地中海料理',
    b3c: 'b-orange'
  },
  // 歐洲 9天 ×3
  {
    key: 'eu_9d_a',
    region: 'europe',
    days: 9,
    name: '義大利全覽南北縱走 9天8夜',
    emoji: '🏛️',
    c1: '#fde68a',
    c2: '#818cf8',
    price: 108000,
    meta: '義大利全境・小團10人・♿無障礙',
    tags: 'europe accessible easy',
    tip: '義大利全覽',
    tipClass: 'b-orange',
    b1: '♿ 無障礙',
    b1c: 'b-green',
    b2: '🏛️ 古蹟全覽',
    b2c: 'b-orange',
    b3: '🍝 義式美食',
    b3c: 'b-orange'
  },
  {
    key: 'eu_9d_b',
    region: 'europe',
    days: 9,
    name: '法德荷三國文化漫遊 9天8夜',
    emoji: '🌷',
    c1: '#60a5fa',
    c2: '#fbbf24',
    price: 105000,
    meta: '法德荷三國・小團12人・♿無障礙',
    tags: 'europe accessible easy',
    tip: '三國文化',
    tipClass: 'b-blue',
    b1: '♿ 無障礙',
    b1c: 'b-green',
    b2: '🌷 文化薈萃',
    b2c: 'b-blue',
    b3: '🚌 全程專車',
    b3c: 'b-blue'
  },
  {
    key: 'eu_9d_c',
    region: 'europe',
    days: 9,
    name: '英國蘇格蘭威爾斯深度 9天8夜',
    emoji: '🏰',
    c1: '#818cf8',
    c2: '#4ade80',
    price: 102000,
    meta: '英國全境・小團10人・♿無障礙',
    tags: 'europe accessible easy',
    tip: '英倫深度',
    tipClass: 'b-blue',
    b1: '♿ 無障礙',
    b1c: 'b-green',
    b2: '🏰 城堡探秘',
    b2c: 'b-blue',
    b3: '🍵 英式下午茶',
    b3c: 'b-teal'
  },
  // 歐洲 11天 ×3
  {
    key: 'eu_11d_a',
    region: 'europe',
    days: 11,
    name: '中歐五國精華捷奧匈斯洛 11天10夜',
    emoji: '🏘️',
    c1: '#fca5a5',
    c2: '#a78bfa',
    price: 122000,
    meta: '中歐五國・小團10人・♿無障礙',
    tags: 'europe accessible',
    tip: '中歐精選',
    tipClass: 'b-purple',
    b1: '♿ 無障礙',
    b1c: 'b-green',
    b2: '🏘️ 童話小城',
    b2c: 'b-purple',
    b3: '🚌 全程專車',
    b3c: 'b-blue'
  },
  {
    key: 'eu_11d_b',
    region: 'europe',
    days: 11,
    name: '西歐五國英法德比荷 11天10夜',
    emoji: '🌷',
    c1: '#60a5fa',
    c2: '#f472b6',
    price: 125000,
    meta: '西歐五國・小團10人・♿無障礙',
    tags: 'europe accessible',
    tip: '西歐精選',
    tipClass: 'b-blue',
    b1: '♿ 無障礙',
    b1c: 'b-green',
    b2: '🌷 五國文化',
    b2c: 'b-blue',
    b3: '🏥 醫療保障',
    b3c: 'b-blue'
  },
  {
    key: 'eu_11d_c',
    region: 'europe',
    days: 11,
    name: '南歐陽光義希土三國 11天10夜',
    emoji: '☀️',
    c1: '#fde68a',
    c2: '#38bdf8',
    price: 118000,
    meta: '南歐三國・小團10人・♿無障礙',
    tags: 'europe accessible',
    tip: '南歐陽光',
    tipClass: 'b-orange',
    b1: '♿ 無障礙',
    b1c: 'b-green',
    b2: '☀️ 陽光地中海',
    b2c: 'b-orange',
    b3: '🍷 南歐美食',
    b3c: 'b-orange'
  },
  // 歐洲 13天 ×3
  {
    key: 'eu_13d_a',
    region: 'europe',
    days: 13,
    name: '歐洲鐵道慢遊六國精選 13天12夜',
    emoji: '🚂',
    c1: '#818cf8',
    c2: '#fbbf24',
    price: 158000,
    meta: '歐洲六國・小團10人・♿無障礙',
    tags: 'europe accessible',
    tip: '鐵道之旅',
    tipClass: 'b-blue',
    b1: '♿ 無障礙',
    b1c: 'b-green',
    b2: '🚂 鐵道漫遊',
    b2c: 'b-blue',
    b3: '🏥 醫療保障',
    b3c: 'b-blue'
  },
  {
    key: 'eu_13d_b',
    region: 'europe',
    days: 13,
    name: '北歐挪威峽灣丹麥芬蘭 13天12夜',
    emoji: '🌊',
    c1: '#bfdbfe',
    c2: '#818cf8',
    price: 165000,
    meta: '北歐三國・小團8人・♿無障礙',
    tags: 'europe accessible',
    tip: '北歐峽灣',
    tipClass: 'b-blue',
    b1: '♿ 無障礙',
    b1c: 'b-green',
    b2: '🌊 峽灣奇景',
    b2c: 'b-blue',
    b3: '🌌 極光之旅',
    b3c: 'b-purple'
  },
  {
    key: 'eu_13d_c',
    region: 'europe',
    days: 13,
    name: '東歐波羅的海三國秘境 13天12夜',
    emoji: '🏰',
    c1: '#a78bfa',
    c2: '#38bdf8',
    price: 148000,
    meta: '波羅的海三國・小團10人・♿無障礙',
    tags: 'europe accessible',
    tip: '秘境探索',
    tipClass: 'b-purple',
    b1: '♿ 無障礙',
    b1c: 'b-green',
    b2: '🏰 古城漫步',
    b2c: 'b-purple',
    b3: '🚌 全程專車',
    b3c: 'b-blue'
  },

  // ===================== EUROPE 歐洲 (33 tours) =====================
  // 7天 ×3
  {
    key: 'eu_uk7d',
    region: 'europe',
    days: 7,
    name: '英國倫敦愛丁堡 7天6夜',
    emoji: '🏰',
    c1: '#60a5fa',
    c2: '#f472b6',
    price: 88000,
    meta: '英國・小團12人・♿無障礙',
    tags: 'europe accessible easy',
    tip: '英倫首選',
    tipClass: 'b-blue',
    b1: '♿ 無障礙',
    b1c: 'b-green',
    b2: '🏰 皇室文化',
    b2c: 'b-blue',
    b3: '🚌 全程專車',
    b3c: 'b-blue'
  },
  {
    key: 'eu_7d_b',
    region: 'europe',
    days: 7,
    name: '法國巴黎普羅旺斯 7天6夜',
    emoji: '🗼',
    c1: '#c4b5fd',
    c2: '#fbbf24',
    price: 92000,
    meta: '法國・小團12人・♿無障礙',
    tags: 'europe accessible easy',
    tip: '浪漫首選',
    tipClass: 'b-purple',
    b1: '♿ 無障礙',
    b1c: 'b-green',
    b2: '🗼 浪漫巴黎',
    b2c: 'b-purple',
    b3: '🍷 法式料理',
    b3c: 'b-orange'
  },
  {
    key: 'eu_7d_c',
    region: 'europe',
    days: 7,
    name: '義大利羅馬佛羅倫斯 7天6夜',
    emoji: '🏛️',
    c1: '#fde68a',
    c2: '#f97316',
    price: 89000,
    meta: '義大利・小團12人・♿無障礙',
    tags: 'europe accessible easy',
    tip: '文藝之旅',
    tipClass: 'b-orange',
    b1: '♿ 無障礙',
    b1c: 'b-green',
    b2: '🏛️ 古蹟巡禮',
    b2c: 'b-orange',
    b3: '🍝 義式料理',
    b3c: 'b-orange'
  },
  // 8天 ×3
  {
    key: 'eu_spain8d',
    region: 'europe',
    days: 8,
    name: '西班牙巴塞隆納馬德里 8天7夜',
    emoji: '💃',
    c1: '#f97316',
    c2: '#fbbf24',
    price: 98000,
    meta: '西班牙・小團12人・♿無障礙',
    tags: 'europe accessible easy',
    tip: '伊比利風情',
    tipClass: 'b-orange',
    b1: '♿ 無障礙',
    b1c: 'b-green',
    b2: '💃 西班牙風情',
    b2c: 'b-orange',
    b3: '🍷 美食美酒',
    b3c: 'b-orange'
  },
  {
    key: 'eu_8d_b',
    region: 'europe',
    days: 8,
    name: '荷蘭比利時風車鬱金香 8天7夜',
    emoji: '🌷',
    c1: '#f9a8d4',
    c2: '#38bdf8',
    price: 96000,
    meta: '荷蘭・比利時・小團12人・♿無障礙',
    tags: 'europe accessible easy',
    tip: '花卉之旅',
    tipClass: 'b-green',
    b1: '♿ 無障礙',
    b1c: 'b-green',
    b2: '🌷 花卉王國',
    b2c: 'b-green',
    b3: '🚌 全程專車',
    b3c: 'b-blue'
  },
  {
    key: 'eu_8d_c',
    region: 'europe',
    days: 8,
    name: '德國羅曼蒂克大道巴伐利亞 8天7夜',
    emoji: '🏰',
    c1: '#fbbf24',
    c2: '#818cf8',
    price: 95000,
    meta: '德國・小團12人・♿無障礙',
    tags: 'europe accessible easy',
    tip: '德意志精選',
    tipClass: 'b-blue',
    b1: '♿ 無障礙',
    b1c: 'b-green',
    b2: '🏰 童話城堡',
    b2c: 'b-blue',
    b3: '🍺 德式美食',
    b3c: 'b-orange'
  },
  // 10天 ×3
  {
    key: 'eu_swiss10d',
    region: 'europe',
    days: 10,
    name: '瑞士奧地利阿爾卑斯 10天9夜',
    emoji: '🏔️',
    c1: '#bfdbfe',
    c2: '#a78bfa',
    price: 128000,
    meta: '瑞士・奧地利・小團10人・♿無障礙',
    tags: 'europe accessible',
    tip: '阿爾卑斯',
    tipClass: 'b-blue',
    b1: '♿ 無障礙',
    b1c: 'b-green',
    b2: '🏔️ 山岳奇景',
    b2c: 'b-blue',
    b3: '🚂 冰河列車',
    b3c: 'b-teal'
  },
  {
    key: 'eu_10d_b',
    region: 'europe',
    days: 10,
    name: '希臘愛琴海島嶼巡禮 10天9夜',
    emoji: '🌊',
    c1: '#38bdf8',
    c2: '#fbbf24',
    price: 118000,
    meta: '希臘・愛琴海・小團10人・♿無障礙',
    tags: 'europe accessible easy',
    tip: '愛琴海夢',
    tipClass: 'b-teal',
    b1: '♿ 無障礙',
    b1c: 'b-green',
    b2: '🌊 藍海療癒',
    b2c: 'b-teal',
    b3: '🍷 地中海料理',
    b3c: 'b-orange'
  },
  {
    key: 'eu_10d_c',
    region: 'europe',
    days: 10,
    name: '捷克波蘭東歐童話小鎮 10天9夜',
    emoji: '🏘️',
    c1: '#fca5a5',
    c2: '#818cf8',
    price: 112000,
    meta: '捷克・波蘭・小團12人・♿無障礙',
    tags: 'europe accessible easy',
    tip: '童話小鎮',
    tipClass: 'b-purple',
    b1: '♿ 無障礙',
    b1c: 'b-green',
    b2: '🏘️ 童話風情',
    b2c: 'b-purple',
    b3: '🚌 全程專車',
    b3c: 'b-blue'
  },
  // 12天 ×3
  {
    key: 'europe',
    region: 'europe',
    days: 12,
    name: '歐洲三國慢遊 12天11夜',
    emoji: '🏛️',
    c1: '#60a5fa',
    c2: '#a78bfa',
    price: 128000,
    meta: '法義瑞・小團12人',
    tags: 'europe accessible',
    tip: '精選',
    tipClass: 'b-blue',
    b1: '🏥 醫療保障',
    b1c: 'b-blue',
    b2: '🚌 全程專車',
    b2c: 'b-orange',
    b3: '',
    b3c: ''
  },
  {
    key: 'eu_nordic12d',
    region: 'europe',
    days: 12,
    name: '北歐四國峽灣極光 12天11夜',
    emoji: '🌌',
    c1: '#818cf8',
    c2: '#38bdf8',
    price: 158000,
    meta: '北歐四國・小團10人・♿無障礙',
    tags: 'europe accessible',
    tip: '極光追尋',
    tipClass: 'b-blue',
    b1: '♿ 無障礙',
    b1c: 'b-green',
    b2: '🌌 極光奇景',
    b2c: 'b-blue',
    b3: '🏥 醫療保障',
    b3c: 'b-blue'
  },
  {
    key: 'eu_12d_c',
    region: 'europe',
    days: 12,
    name: '葡萄牙西班牙伊比利深度 12天11夜',
    emoji: '⛵',
    c1: '#fbbf24',
    c2: '#f472b6',
    price: 138000,
    meta: '葡萄牙・西班牙・小團10人・♿無障礙',
    tags: 'europe accessible',
    tip: '伊比利深度',
    tipClass: 'b-purple',
    b1: '♿ 無障礙',
    b1c: 'b-green',
    b2: '⛵ 大航海風情',
    b2c: 'b-purple',
    b3: '🍷 美酒佳餚',
    b3c: 'b-orange'
  },
  // 14天 ×3
  {
    key: 'eu_east14d',
    region: 'europe',
    days: 14,
    name: '東歐五國古堡波光 14天13夜',
    emoji: '🏰',
    c1: '#a78bfa',
    c2: '#fbbf24',
    price: 168000,
    meta: '東歐五國・小團10人・♿無障礙',
    tags: 'europe accessible',
    tip: '東歐精選',
    tipClass: 'b-purple',
    b1: '♿ 無障礙',
    b1c: 'b-green',
    b2: '🏰 古堡巡禮',
    b2c: 'b-purple',
    b3: '🚌 全程專車',
    b3c: 'b-blue'
  },
  {
    key: 'eu_14d_b',
    region: 'europe',
    days: 14,
    name: '西歐四國精選慢旅 14天13夜',
    emoji: '🗼',
    c1: '#60a5fa',
    c2: '#f97316',
    price: 162000,
    meta: '西歐四國・小團10人・♿無障礙',
    tags: 'europe accessible',
    tip: '西歐精選',
    tipClass: 'b-blue',
    b1: '♿ 無障礙',
    b1c: 'b-green',
    b2: '🗼 西歐精選',
    b2c: 'b-blue',
    b3: '🏥 醫療保障',
    b3c: 'b-blue'
  },
  {
    key: 'eu_14d_c',
    region: 'europe',
    days: 14,
    name: '地中海郵輪義希土 14天13夜',
    emoji: '🚢',
    c1: '#38bdf8',
    c2: '#818cf8',
    price: 178000,
    meta: '地中海・小團12人・♿無障礙',
    tags: 'europe accessible',
    tip: '郵輪豪華',
    tipClass: 'b-blue',
    b1: '♿ 無障礙',
    b1c: 'b-green',
    b2: '🚢 豪華郵輪',
    b2c: 'b-blue',
    b3: '🍷 美食美酒',
    b3c: 'b-orange'
  },
  // 15天 ×3
  {
    key: 'eu_med15d',
    region: 'europe',
    days: 15,
    name: '地中海全覽義法西 15天14夜',
    emoji: '🌊',
    c1: '#818cf8',
    c2: '#f97316',
    price: 188000,
    meta: '地中海三國・小團10人・♿無障礙',
    tags: 'europe accessible',
    tip: '地中海精選',
    tipClass: 'b-blue',
    b1: '♿ 無障礙',
    b1c: 'b-green',
    b2: '🌊 地中海風光',
    b2c: 'b-blue',
    b3: '🏥 醫療保障',
    b3c: 'b-blue'
  },
  {
    key: 'eu_15d_b',
    region: 'europe',
    days: 15,
    name: '北歐冰島格陵蘭極地探秘 15天14夜',
    emoji: '🧊',
    c1: '#bfdbfe',
    c2: '#6ee7b7',
    price: 198000,
    meta: '北歐・冰島・小團8人・♿無障礙',
    tags: 'europe accessible',
    tip: '極地探秘',
    tipClass: 'b-blue',
    b1: '♿ 無障礙',
    b1c: 'b-green',
    b2: '🧊 冰川奇景',
    b2c: 'b-blue',
    b3: '🌌 極光之旅',
    b3c: 'b-purple'
  },
  {
    key: 'eu_15d_c',
    region: 'europe',
    days: 15,
    name: '英法德三國文化深度 15天14夜',
    emoji: '🏛️',
    c1: '#c4b5fd',
    c2: '#fbbf24',
    price: 185000,
    meta: '英法德三國・小團10人・♿無障礙',
    tags: 'europe accessible',
    tip: '文化深度',
    tipClass: 'b-purple',
    b1: '♿ 無障礙',
    b1c: 'b-green',
    b2: '🏛️ 文化深度',
    b2c: 'b-purple',
    b3: '🏥 醫療保障',
    b3c: 'b-blue'
  },

  // ===================== SEA 東南亞 (33 tours) =====================
  // 4天 ×3
  {
    key: 'sea_thai4d',
    region: 'sea',
    days: 4,
    name: '泰國曼谷華欣 4天3夜',
    emoji: '🐘',
    c1: '#fbbf24',
    c2: '#f97316',
    price: 22800,
    meta: '泰國・小團12人・♿無障礙',
    tags: 'sea easy accessible',
    tip: '微笑國度',
    tipClass: 'b-orange',
    b1: '♿ 無障礙',
    b1c: 'b-green',
    b2: '🐘 文化體驗',
    b2c: 'b-orange',
    b3: '🍜 泰式料理',
    b3c: 'b-orange'
  },
  {
    key: 'sea_4d_b',
    region: 'sea',
    days: 4,
    name: '新加坡濱海灣花園城市 4天3夜',
    emoji: '🌺',
    c1: '#4ade80',
    c2: '#38bdf8',
    price: 28800,
    meta: '新加坡・小團12人・♿無障礙',
    tags: 'sea easy accessible',
    tip: '花園城市',
    tipClass: 'b-teal',
    b1: '♿ 無障礙',
    b1c: 'b-green',
    b2: '🌺 花園漫步',
    b2c: 'b-teal',
    b3: '🍜 多元美食',
    b3c: 'b-orange'
  },
  {
    key: 'sea_4d_c',
    region: 'sea',
    days: 4,
    name: '馬來西亞吉隆坡檳城 4天3夜',
    emoji: '🕌',
    c1: '#fde68a',
    c2: '#4ade80',
    price: 21800,
    meta: '馬來西亞・小團12人・♿無障礙',
    tags: 'sea easy accessible',
    tip: '多元文化',
    tipClass: 'b-orange',
    b1: '♿ 無障礙',
    b1c: 'b-green',
    b2: '🕌 文化薈萃',
    b2c: 'b-orange',
    b3: '🍜 南洋美食',
    b3c: 'b-orange'
  },
  // 5天 ×3
  {
    key: 'bali',
    region: 'sea',
    days: 5,
    name: '峇里島悠閒海景療癒 5天4夜',
    emoji: '🌺',
    c1: '#4ade80',
    c2: '#facc15',
    price: 38800,
    meta: '印尼峇里島・小團10人・♿無障礙',
    tags: 'sea accessible easy',
    tip: '熱帶天堂',
    tipClass: 'b-teal',
    b1: '♿ 無障礙',
    b1c: 'b-green',
    b2: '🌊 海景療癒',
    b2c: 'b-teal',
    b3: '',
    b3c: ''
  },
  {
    key: 'sea_cam5d',
    region: 'sea',
    days: 5,
    name: '柬埔寨吳哥窟文化 5天4夜',
    emoji: '🏛️',
    c1: '#fbbf24',
    c2: '#f97316',
    price: 28800,
    meta: '柬埔寨吳哥・小團12人・♿無障礙',
    tags: 'sea accessible easy',
    tip: '古文明',
    tipClass: 'b-orange',
    b1: '♿ 無障礙',
    b1c: 'b-green',
    b2: '🏛️ 古蹟探秘',
    b2c: 'b-orange',
    b3: '🚌 全程專車',
    b3c: 'b-blue'
  },
  {
    key: 'sea_5d_c',
    region: 'sea',
    days: 5,
    name: '越南胡志明峴港慢遊 5天4夜',
    emoji: '🏮',
    c1: '#fca5a5',
    c2: '#fbbf24',
    price: 25800,
    meta: '越南・小團12人・♿無障礙',
    tags: 'sea easy accessible',
    tip: '越南精選',
    tipClass: 'b-orange',
    b1: '♿ 無障礙',
    b1c: 'b-green',
    b2: '🏮 古城文化',
    b2c: 'b-orange',
    b3: '🍜 越式料理',
    b3c: 'b-orange'
  },
  // 6天 ×3
  {
    key: 'sea_thai6d',
    region: 'sea',
    days: 6,
    name: '泰國清邁曼谷美食文化 6天5夜',
    emoji: '🌸',
    c1: '#86efac',
    c2: '#fbbf24',
    price: 32800,
    meta: '泰國北南・小團10人・♿無障礙',
    tags: 'sea easy accessible',
    tip: '泰北精選',
    tipClass: 'b-teal',
    b1: '♿ 無障礙',
    b1c: 'b-green',
    b2: '🌸 清邁花市',
    b2c: 'b-teal',
    b3: '🍜 泰式料理',
    b3c: 'b-orange'
  },
  {
    key: 'sea_palawan6d',
    region: 'sea',
    days: 6,
    name: '菲律賓巴拉望秘境海島 6天5夜',
    emoji: '🏝️',
    c1: '#22d3ee',
    c2: '#4ade80',
    price: 35800,
    meta: '菲律賓巴拉望・小團10人・♿無障礙',
    tags: 'sea accessible easy',
    tip: '秘境海島',
    tipClass: 'b-teal',
    b1: '♿ 無障礙',
    b1c: 'b-green',
    b2: '🏝️ 秘境探索',
    b2c: 'b-teal',
    b3: '🌊 潛水體驗',
    b3c: 'b-blue'
  },
  {
    key: 'sea_6d_c',
    region: 'sea',
    days: 6,
    name: '峇里島龍目島雙島療癒 6天5夜',
    emoji: '🌺',
    c1: '#34d399',
    c2: '#a78bfa',
    price: 36800,
    meta: '印尼峇里龍目・小團10人・♿無障礙',
    tags: 'sea accessible easy',
    tip: '雙島天堂',
    tipClass: 'b-teal',
    b1: '♿ 無障礙',
    b1c: 'b-green',
    b2: '🌺 熱帶天堂',
    b2c: 'b-teal',
    b3: '🌊 海島療癒',
    b3c: 'b-blue'
  },
  // 7天 ×3
  {
    key: 'sea_sg7d',
    region: 'sea',
    days: 7,
    name: '新馬雙城美食文化 7天6夜',
    emoji: '🦁',
    c1: '#fbbf24',
    c2: '#4ade80',
    price: 38800,
    meta: '新加坡・馬來西亞・小團12人・♿無障礙',
    tags: 'sea easy accessible',
    tip: '雙城精選',
    tipClass: 'b-teal',
    b1: '♿ 無障礙',
    b1c: 'b-green',
    b2: '🦁 花園城市',
    b2c: 'b-teal',
    b3: '🍜 多元美食',
    b3c: 'b-orange'
  },
  {
    key: 'sea_7d_b',
    region: 'sea',
    days: 7,
    name: '緬甸蒲甘佛塔古城 7天6夜',
    emoji: '🛕',
    c1: '#fbbf24',
    c2: '#f97316',
    price: 32800,
    meta: '緬甸蒲甘・小團12人・♿無障礙',
    tags: 'sea accessible',
    tip: '佛塔古城',
    tipClass: 'b-orange',
    b1: '♿ 無障礙',
    b1c: 'b-green',
    b2: '🛕 佛塔文化',
    b2c: 'b-orange',
    b3: '🚌 全程專車',
    b3c: 'b-blue'
  },
  {
    key: 'sea_7d_c',
    region: 'sea',
    days: 7,
    name: '印尼爪哇婆羅浮屠 7天6夜',
    emoji: '🏛️',
    c1: '#86efac',
    c2: '#fbbf24',
    price: 34800,
    meta: '印尼爪哇・小團12人・♿無障礙',
    tags: 'sea accessible',
    tip: '古文明探秘',
    tipClass: 'b-orange',
    b1: '♿ 無障礙',
    b1c: 'b-green',
    b2: '🏛️ 世界遺產',
    b2c: 'b-orange',
    b3: '🚌 全程專車',
    b3c: 'b-blue'
  },
  // 8天 ×3
  {
    key: 'sea_viet8d',
    region: 'sea',
    days: 8,
    name: '越南全覽河內下龍灣會安 8天7夜',
    emoji: '🏮',
    c1: '#fca5a5',
    c2: '#86efac',
    price: 39800,
    meta: '越南南北・小團10人・♿無障礙',
    tags: 'sea easy accessible',
    tip: '越南全覽',
    tipClass: 'b-teal',
    b1: '♿ 無障礙',
    b1c: 'b-green',
    b2: '🏮 下龍灣奇景',
    b2c: 'b-teal',
    b3: '🍜 越式美食',
    b3c: 'b-orange'
  },
  {
    key: 'sea_8d_b',
    region: 'sea',
    days: 8,
    name: '泰國普吉蘇梅島雙島 8天7夜',
    emoji: '🏖️',
    c1: '#22d3ee',
    c2: '#fbbf24',
    price: 42800,
    meta: '泰國南部・小團10人・♿無障礙',
    tags: 'sea easy accessible',
    tip: '雙島天堂',
    tipClass: 'b-teal',
    b1: '♿ 無障礙',
    b1c: 'b-green',
    b2: '🏖️ 海島療癒',
    b2c: 'b-teal',
    b3: '🌊 藍海美景',
    b3c: 'b-blue'
  },
  {
    key: 'sea_8d_c',
    region: 'sea',
    days: 8,
    name: '馬來西亞沙巴婆羅洲雨林 8天7夜',
    emoji: '🌿',
    c1: '#4ade80',
    c2: '#fbbf24',
    price: 38800,
    meta: '馬來西亞沙巴・小團10人・♿無障礙',
    tags: 'sea accessible',
    tip: '雨林探秘',
    tipClass: 'b-green',
    b1: '♿ 無障礙',
    b1c: 'b-green',
    b2: '🌿 雨林生態',
    b2c: 'b-green',
    b3: '🦧 動物探索',
    b3c: 'b-teal'
  },
  // SEA 3天 ×3
  {
    key: 'sea_3d_a',
    region: 'sea',
    days: 3,
    name: '新加坡花園城市輕鬆 3天2夜',
    emoji: '🌺',
    c1: '#34d399',
    c2: '#38bdf8',
    price: 18800,
    meta: '新加坡・小團12人・♿無障礙',
    tags: 'sea easy accessible',
    tip: '輕鬆初遊',
    tipClass: 'b-teal',
    b1: '♿ 無障礙',
    b1c: 'b-green',
    b2: '🌺 花園城市',
    b2c: 'b-teal',
    b3: '🍜 南洋美食',
    b3c: 'b-orange'
  },
  {
    key: 'sea_3d_b',
    region: 'sea',
    days: 3,
    name: '泰國曼谷短遊精選 3天2夜',
    emoji: '🐘',
    c1: '#fbbf24',
    c2: '#4ade80',
    price: 16800,
    meta: '泰國曼谷・小團12人・♿無障礙',
    tags: 'sea easy accessible',
    tip: '曼谷精選',
    tipClass: 'b-orange',
    b1: '♿ 無障礙',
    b1c: 'b-green',
    b2: '🐘 文化體驗',
    b2c: 'b-orange',
    b3: '🍜 泰式料理',
    b3c: 'b-orange'
  },
  {
    key: 'sea_3d_c',
    region: 'sea',
    days: 3,
    name: '馬來西亞吉隆坡城市探索 3天2夜',
    emoji: '🕌',
    c1: '#fde68a',
    c2: '#86efac',
    price: 15800,
    meta: '馬來西亞吉隆坡・小團12人・♿無障礙',
    tags: 'sea easy accessible',
    tip: '城市精選',
    tipClass: 'b-orange',
    b1: '♿ 無障礙',
    b1c: 'b-green',
    b2: '🕌 多元文化',
    b2c: 'b-orange',
    b3: '🚌 全程專車',
    b3c: 'b-blue'
  },
  // SEA 9天 ×3
  {
    key: 'sea_9d_a',
    region: 'sea',
    days: 9,
    name: '泰國北中南全覽文化 9天8夜',
    emoji: '🐘',
    c1: '#fbbf24',
    c2: '#818cf8',
    price: 45800,
    meta: '泰國全境・小團10人・♿無障礙',
    tags: 'sea accessible easy',
    tip: '泰國全覽',
    tipClass: 'b-orange',
    b1: '♿ 無障礙',
    b1c: 'b-green',
    b2: '🐘 全境探索',
    b2c: 'b-orange',
    b3: '🍜 泰式美食',
    b3c: 'b-orange'
  },
  {
    key: 'sea_9d_b',
    region: 'sea',
    days: 9,
    name: '新馬泰三國文化美食 9天8夜',
    emoji: '🌴',
    c1: '#4ade80',
    c2: '#fbbf24',
    price: 42800,
    meta: '新馬泰三國・小團10人・♿無障礙',
    tags: 'sea easy accessible',
    tip: '三國精選',
    tipClass: 'b-teal',
    b1: '♿ 無障礙',
    b1c: 'b-green',
    b2: '🌴 南洋風情',
    b2c: 'b-teal',
    b3: '🍜 多國美食',
    b3c: 'b-orange'
  },
  {
    key: 'sea_9d_c',
    region: 'sea',
    days: 9,
    name: '越南全程北中南完整 9天8夜',
    emoji: '🏮',
    c1: '#fca5a5',
    c2: '#4ade80',
    price: 40800,
    meta: '越南全境・小團10人・♿無障礙',
    tags: 'sea easy accessible',
    tip: '越南完整',
    tipClass: 'b-teal',
    b1: '♿ 無障礙',
    b1c: 'b-green',
    b2: '🏮 越南文化',
    b2c: 'b-teal',
    b3: '🍜 越式美食',
    b3c: 'b-orange'
  },
  // SEA 11天 ×3
  {
    key: 'sea_11d_a',
    region: 'sea',
    days: 11,
    name: '東南亞精選郵輪之旅 11天10夜',
    emoji: '🚢',
    c1: '#38bdf8',
    c2: '#4ade80',
    price: 55800,
    meta: '東南亞海域・小團12人・♿無障礙',
    tags: 'sea accessible',
    tip: '郵輪精選',
    tipClass: 'b-blue',
    b1: '♿ 無障礙',
    b1c: 'b-green',
    b2: '🚢 豪華郵輪',
    b2c: 'b-blue',
    b3: '🍜 多元料理',
    b3c: 'b-orange'
  },
  {
    key: 'sea_11d_b',
    region: 'sea',
    days: 11,
    name: '印尼峇里爪哇蘇拉維西 11天10夜',
    emoji: '🌺',
    c1: '#86efac',
    c2: '#f97316',
    price: 52800,
    meta: '印尼多島・小團10人・♿無障礙',
    tags: 'sea accessible',
    tip: '印尼深度',
    tipClass: 'b-orange',
    b1: '♿ 無障礙',
    b1c: 'b-green',
    b2: '🌺 多島探索',
    b2c: 'b-orange',
    b3: '🏛️ 世界遺產',
    b3c: 'b-purple'
  },
  {
    key: 'sea_11d_c',
    region: 'sea',
    days: 11,
    name: '中南半島完整四國深度 11天10夜',
    emoji: '🛕',
    c1: '#fbbf24',
    c2: '#a78bfa',
    price: 50800,
    meta: '中南半島四國・小團10人・♿無障礙',
    tags: 'sea accessible',
    tip: '四國深度',
    tipClass: 'b-purple',
    b1: '♿ 無障礙',
    b1c: 'b-green',
    b2: '🛕 古城文化',
    b2c: 'b-purple',
    b3: '🚌 全程專車',
    b3c: 'b-blue'
  },
  // SEA 14天 ×3
  {
    key: 'sea_14d_a',
    region: 'sea',
    days: 14,
    name: '東南亞六國文化深度之旅 14天13夜',
    emoji: '🌏',
    c1: '#4ade80',
    c2: '#f472b6',
    price: 65800,
    meta: '東南亞六國・小團10人・♿無障礙',
    tags: 'sea accessible',
    tip: '六國精選',
    tipClass: 'b-purple',
    b1: '♿ 無障礙',
    b1c: 'b-green',
    b2: '🌏 深度探索',
    b2c: 'b-purple',
    b3: '🏥 醫療保障',
    b3c: 'b-blue'
  },
  {
    key: 'sea_14d_b',
    region: 'sea',
    days: 14,
    name: '泰緬寮柬越完整中南半島 14天13夜',
    emoji: '🛶',
    c1: '#fbbf24',
    c2: '#38bdf8',
    price: 62800,
    meta: '中南半島五國・小團10人・♿無障礙',
    tags: 'sea accessible',
    tip: '半島全覽',
    tipClass: 'b-teal',
    b1: '♿ 無障礙',
    b1c: 'b-green',
    b2: '🛶 半島探索',
    b2c: 'b-teal',
    b3: '🚌 全程專車',
    b3c: 'b-blue'
  },
  {
    key: 'sea_14d_c',
    region: 'sea',
    days: 14,
    name: '東南亞銀髮養生度假精選 14天13夜',
    emoji: '🌿',
    c1: '#86efac',
    c2: '#818cf8',
    price: 58800,
    meta: '東南亞度假勝地・小團10人・♿無障礙',
    tags: 'sea easy accessible',
    tip: '養生度假',
    tipClass: 'b-green',
    b1: '♿ 無障礙',
    b1c: 'b-green',
    b2: '🌿 養生療癒',
    b2c: 'b-green',
    b3: '🏥 醫療保障',
    b3c: 'b-blue'
  },
  // 10天 ×3
  {
    key: 'sea_10d_a',
    region: 'sea',
    days: 10,
    name: '東南亞四國精選慢旅 10天9夜',
    emoji: '🌏',
    c1: '#fbbf24',
    c2: '#4ade80',
    price: 48800,
    meta: '東南亞四國・小團10人・♿無障礙',
    tags: 'sea accessible easy',
    tip: '四國精選',
    tipClass: 'b-teal',
    b1: '♿ 無障礙',
    b1c: 'b-green',
    b2: '🌏 多國探索',
    b2c: 'b-teal',
    b3: '🚌 全程專車',
    b3c: 'b-blue'
  },
  {
    key: 'sea_10d_b',
    region: 'sea',
    days: 10,
    name: '印尼峇里爪哇文化深度 10天9夜',
    emoji: '🌺',
    c1: '#86efac',
    c2: '#f97316',
    price: 46800,
    meta: '印尼・小團10人・♿無障礙',
    tags: 'sea accessible',
    tip: '印尼深度',
    tipClass: 'b-orange',
    b1: '♿ 無障礙',
    b1c: 'b-green',
    b2: '🌺 文化探索',
    b2c: 'b-orange',
    b3: '🏛️ 世界遺產',
    b3c: 'b-purple'
  },
  {
    key: 'sea_10d_c',
    region: 'sea',
    days: 10,
    name: '湄公河金三角古都巡禮 10天9夜',
    emoji: '🛶',
    c1: '#fbbf24',
    c2: '#a78bfa',
    price: 44800,
    meta: '泰緬寮・小團10人・♿無障礙',
    tags: 'sea accessible',
    tip: '金三角探秘',
    tipClass: 'b-orange',
    b1: '♿ 無障礙',
    b1c: 'b-green',
    b2: '🛶 湄公河遊',
    b2c: 'b-orange',
    b3: '🚌 全程專車',
    b3c: 'b-blue'
  },
  // 12天 ×3
  {
    key: 'sea_12d_a',
    region: 'sea',
    days: 12,
    name: '東南亞全覽五國深度 12天11夜',
    emoji: '🌏',
    c1: '#4ade80',
    c2: '#818cf8',
    price: 58800,
    meta: '東南亞五國・小團10人・♿無障礙',
    tags: 'sea accessible',
    tip: '五國全覽',
    tipClass: 'b-purple',
    b1: '♿ 無障礙',
    b1c: 'b-green',
    b2: '🌏 深度探索',
    b2c: 'b-purple',
    b3: '🏥 醫療保障',
    b3c: 'b-blue'
  },
  {
    key: 'sea_12d_b',
    region: 'sea',
    days: 12,
    name: '越南寮國柬埔寨古城慢旅 12天11夜',
    emoji: '🏛️',
    c1: '#fca5a5',
    c2: '#fbbf24',
    price: 52800,
    meta: '中南半島三國・小團10人・♿無障礙',
    tags: 'sea accessible',
    tip: '古城慢旅',
    tipClass: 'b-orange',
    b1: '♿ 無障礙',
    b1c: 'b-green',
    b2: '🏛️ 古城文化',
    b2c: 'b-orange',
    b3: '🚌 全程專車',
    b3c: 'b-blue'
  },
  {
    key: 'sea_12d_c',
    region: 'sea',
    days: 12,
    name: '馬來西亞全境海陸雙享 12天11夜',
    emoji: '🌴',
    c1: '#34d399',
    c2: '#fbbf24',
    price: 54800,
    meta: '馬來西亞・小團10人・♿無障礙',
    tags: 'sea accessible easy',
    tip: '馬來全境',
    tipClass: 'b-teal',
    b1: '♿ 無障礙',
    b1c: 'b-green',
    b2: '🌴 海陸雙享',
    b2c: 'b-teal',
    b3: '🍜 南洋美食',
    b3c: 'b-orange'
  },

  // ===================== NORTHEAST 東北亞 (33 tours) =====================
  // 4天 ×3
  {
    key: 'ne_seoul4d',
    region: 'northeast',
    days: 4,
    name: '首爾景福宮明洞美食 4天3夜',
    emoji: '🏯',
    c1: '#fca5a5',
    c2: '#818cf8',
    price: 28800,
    meta: '韓國首爾・小團12人・♿無障礙',
    tags: 'northeast easy accessible',
    tip: '韓流首選',
    tipClass: 'b-purple',
    b1: '♿ 無障礙',
    b1c: 'b-green',
    b2: '🏯 宮廷文化',
    b2c: 'b-purple',
    b3: '🍜 韓式料理',
    b3c: 'b-orange'
  },
  {
    key: 'ne_4d_b',
    region: 'northeast',
    days: 4,
    name: '首爾仁川北村韓屋 4天3夜',
    emoji: '🏘️',
    c1: '#fbbf24',
    c2: '#f472b6',
    price: 27800,
    meta: '韓國首爾仁川・小團12人・♿無障礙',
    tags: 'northeast easy accessible',
    tip: '韓屋體驗',
    tipClass: 'b-orange',
    b1: '♿ 無障礙',
    b1c: 'b-green',
    b2: '🏘️ 韓屋文化',
    b2c: 'b-orange',
    b3: '🍜 傳統料理',
    b3c: 'b-orange'
  },
  {
    key: 'ne_4d_c',
    region: 'northeast',
    days: 4,
    name: '香港澳門雙城慢遊 4天3夜',
    emoji: '🌃',
    c1: '#fbbf24',
    c2: '#f97316',
    price: 25800,
    meta: '香港・澳門・小團12人・♿無障礙',
    tags: 'northeast easy accessible',
    tip: '雙城精選',
    tipClass: 'b-orange',
    b1: '♿ 無障礙',
    b1c: 'b-green',
    b2: '🌃 夜景首選',
    b2c: 'b-orange',
    b3: '🍜 港澳美食',
    b3c: 'b-orange'
  },
  // 5天 ×3
  {
    key: 'ne_jeju5d',
    region: 'northeast',
    days: 5,
    name: '濟州島火山海岸自然 5天4夜',
    emoji: '🌋',
    c1: '#4ade80',
    c2: '#38bdf8',
    price: 32800,
    meta: '韓國濟州島・小團10人・♿無障礙',
    tags: 'northeast easy accessible',
    tip: '火山島嶼',
    tipClass: 'b-teal',
    b1: '♿ 無障礙',
    b1c: 'b-green',
    b2: '🌋 自然奇景',
    b2c: 'b-teal',
    b3: '🍜 海鮮料理',
    b3c: 'b-orange'
  },
  {
    key: 'ne_beijing5d',
    region: 'northeast',
    days: 5,
    name: '北京故宮長城萬里 5天4夜',
    emoji: '🏯',
    c1: '#fca5a5',
    c2: '#fbbf24',
    price: 30800,
    meta: '中國北京・小團12人・♿無障礙',
    tags: 'northeast easy accessible',
    tip: '皇城首選',
    tipClass: 'b-orange',
    b1: '♿ 無障礙',
    b1c: 'b-green',
    b2: '🏯 皇城文化',
    b2c: 'b-orange',
    b3: '🚌 全程專車',
    b3c: 'b-blue'
  },
  {
    key: 'ne_5d_c',
    region: 'northeast',
    days: 5,
    name: '韓國釜山慶州歷史文化 5天4夜',
    emoji: '⛩️',
    c1: '#a78bfa',
    c2: '#fbbf24',
    price: 31800,
    meta: '韓國釜山慶州・小團10人・♿無障礙',
    tags: 'northeast easy accessible',
    tip: '古都文化',
    tipClass: 'b-purple',
    b1: '♿ 無障礙',
    b1c: 'b-green',
    b2: '⛩️ 古都巡禮',
    b2c: 'b-purple',
    b3: '🍜 韓式料理',
    b3c: 'b-orange'
  },
  // 6天 ×3
  {
    key: 'ne_6d_a',
    region: 'northeast',
    days: 6,
    name: '中國上海蘇杭江南水鄉 6天5夜',
    emoji: '🌉',
    c1: '#38bdf8',
    c2: '#818cf8',
    price: 32800,
    meta: '中國江南・小團12人・♿無障礙',
    tags: 'northeast easy accessible',
    tip: '江南水鄉',
    tipClass: 'b-blue',
    b1: '♿ 無障礙',
    b1c: 'b-green',
    b2: '🌉 江南風情',
    b2c: 'b-blue',
    b3: '🍜 江南料理',
    b3c: 'b-orange'
  },
  {
    key: 'ne_6d_b',
    region: 'northeast',
    days: 6,
    name: '韓國春川全州溫泉養生 6天5夜',
    emoji: '♨️',
    c1: '#fca5a5',
    c2: '#4ade80',
    price: 34800,
    meta: '韓國中部・小團10人・♿無障礙',
    tags: 'northeast easy accessible',
    tip: '溫泉養生',
    tipClass: 'b-teal',
    b1: '♿ 無障礙',
    b1c: 'b-green',
    b2: '♨️ 溫泉療癒',
    b2c: 'b-teal',
    b3: '🍜 韓式料理',
    b3c: 'b-orange'
  },
  {
    key: 'ne_6d_c',
    region: 'northeast',
    days: 6,
    name: '中國桂林山水漓江遊 6天5夜',
    emoji: '⛰️',
    c1: '#86efac',
    c2: '#38bdf8',
    price: 28800,
    meta: '中國桂林・小團12人・♿無障礙',
    tags: 'northeast easy accessible',
    tip: '山水奇景',
    tipClass: 'b-teal',
    b1: '♿ 無障礙',
    b1c: 'b-green',
    b2: '⛰️ 山水秘境',
    b2c: 'b-teal',
    b3: '🛶 漓江遊船',
    b3c: 'b-blue'
  },
  // 7天 ×3
  {
    key: 'ne_korea7d',
    region: 'northeast',
    days: 7,
    name: '韓國全境首爾釜山濟州 7天6夜',
    emoji: '🇰🇷',
    c1: '#fca5a5',
    c2: '#60a5fa',
    price: 42800,
    meta: '韓國全境・小團10人・♿無障礙',
    tags: 'northeast easy accessible',
    tip: '韓國全境',
    tipClass: 'b-purple',
    b1: '♿ 無障礙',
    b1c: 'b-green',
    b2: '🏯 文化深度',
    b2c: 'b-purple',
    b3: '🍜 韓食饗宴',
    b3c: 'b-orange'
  },
  {
    key: 'ne_mongolia7d',
    region: 'northeast',
    days: 7,
    name: '蒙古草原遊牧文化體驗 7天6夜',
    emoji: '🐎',
    c1: '#fbbf24',
    c2: '#86efac',
    price: 38800,
    meta: '蒙古烏蘭巴托・小團10人・♿無障礙',
    tags: 'northeast accessible',
    tip: '草原奇旅',
    tipClass: 'b-orange',
    b1: '♿ 無障礙',
    b1c: 'b-green',
    b2: '🐎 草原文化',
    b2c: 'b-orange',
    b3: '⛺ 蒙古包住宿',
    b3c: 'b-teal'
  },
  {
    key: 'ne_7d_c',
    region: 'northeast',
    days: 7,
    name: '中國西安兵馬俑古都絲路 7天6夜',
    emoji: '🏺',
    c1: '#fbbf24',
    c2: '#f97316',
    price: 36800,
    meta: '中國西安・小團12人・♿無障礙',
    tags: 'northeast easy accessible',
    tip: '絲路古都',
    tipClass: 'b-orange',
    b1: '♿ 無障礙',
    b1c: 'b-green',
    b2: '🏺 古文明',
    b2c: 'b-orange',
    b3: '🚌 全程專車',
    b3c: 'b-blue'
  },
  // 8天 ×3
  {
    key: 'ne_japankorea8d',
    region: 'northeast',
    days: 8,
    name: '日韓雙國東京首爾精選 8天7夜',
    emoji: '✈️',
    c1: '#fbbf24',
    c2: '#f472b6',
    price: 56800,
    meta: '日本・韓國・小團10人・♿無障礙',
    tags: 'northeast accessible easy',
    tip: '日韓雙享',
    tipClass: 'b-purple',
    b1: '♿ 無障礙',
    b1c: 'b-green',
    b2: '✈️ 雙國精選',
    b2c: 'b-purple',
    b3: '🍱 日韓美食',
    b3c: 'b-orange'
  },
  {
    key: 'ne_8d_b',
    region: 'northeast',
    days: 8,
    name: '中國雲南麗江大理慢活 8天7夜',
    emoji: '🌸',
    c1: '#86efac',
    c2: '#a78bfa',
    price: 38800,
    meta: '中國雲南・小團10人・♿無障礙',
    tags: 'northeast easy accessible',
    tip: '雲南慢活',
    tipClass: 'b-teal',
    b1: '♿ 無障礙',
    b1c: 'b-green',
    b2: '🌸 古城慢遊',
    b2c: 'b-teal',
    b3: '🌿 生態療癒',
    b3c: 'b-green'
  },
  {
    key: 'ne_8d_c',
    region: 'northeast',
    days: 8,
    name: '中國四川成都峨眉樂山 8天7夜',
    emoji: '🐼',
    c1: '#86efac',
    c2: '#fbbf24',
    price: 36800,
    meta: '中國四川・小團12人・♿無障礙',
    tags: 'northeast easy accessible',
    tip: '熊貓故鄉',
    tipClass: 'b-green',
    b1: '♿ 無障礙',
    b1c: 'b-green',
    b2: '🐼 熊貓基地',
    b2c: 'b-green',
    b3: '🍜 川菜料理',
    b3c: 'b-orange'
  },
  // 東北亞 3天 ×3
  {
    key: 'ne_3d_a',
    region: 'northeast',
    days: 3,
    name: '首爾仁川輕旅精選 3天2夜',
    emoji: '🏯',
    c1: '#fca5a5',
    c2: '#818cf8',
    price: 18800,
    meta: '韓國首爾・小團12人・♿無障礙',
    tags: 'northeast easy accessible',
    tip: '輕鬆初遊',
    tipClass: 'b-purple',
    b1: '♿ 無障礙',
    b1c: 'b-green',
    b2: '🏯 首爾精選',
    b2c: 'b-purple',
    b3: '🍜 韓式料理',
    b3c: 'b-orange'
  },
  {
    key: 'ne_3d_b',
    region: 'northeast',
    days: 3,
    name: '香港夜景美食文化 3天2夜',
    emoji: '🌃',
    c1: '#fbbf24',
    c2: '#f97316',
    price: 16800,
    meta: '香港・小團12人・♿無障礙',
    tags: 'northeast easy accessible',
    tip: '香港精選',
    tipClass: 'b-orange',
    b1: '♿ 無障礙',
    b1c: 'b-green',
    b2: '🌃 夜景之都',
    b2c: 'b-orange',
    b3: '🍜 港式美食',
    b3c: 'b-orange'
  },
  {
    key: 'ne_3d_c',
    region: 'northeast',
    days: 3,
    name: '北京天安門天壇故宮 3天2夜',
    emoji: '🏯',
    c1: '#fca5a5',
    c2: '#fbbf24',
    price: 17800,
    meta: '中國北京・小團12人・♿無障礙',
    tags: 'northeast easy accessible',
    tip: '皇城初探',
    tipClass: 'b-orange',
    b1: '♿ 無障礙',
    b1c: 'b-green',
    b2: '🏯 皇城文化',
    b2c: 'b-orange',
    b3: '🚌 全程專車',
    b3c: 'b-blue'
  },
  // 東北亞 9天 ×3
  {
    key: 'ne_9d_a',
    region: 'northeast',
    days: 9,
    name: '韓國全境深度文化美食 9天8夜',
    emoji: '🏯',
    c1: '#fca5a5',
    c2: '#818cf8',
    price: 48800,
    meta: '韓國全境・小團10人・♿無障礙',
    tags: 'northeast accessible easy',
    tip: '韓國深度',
    tipClass: 'b-purple',
    b1: '♿ 無障礙',
    b1c: 'b-green',
    b2: '🏯 文化深度',
    b2c: 'b-purple',
    b3: '🍜 韓食全覽',
    b3c: 'b-orange'
  },
  {
    key: 'ne_9d_b',
    region: 'northeast',
    days: 9,
    name: '中國江南水鄉蘇杭揚 9天8夜',
    emoji: '🌉',
    c1: '#38bdf8',
    c2: '#fbbf24',
    price: 42800,
    meta: '中國江南・小團12人・♿無障礙',
    tags: 'northeast easy accessible',
    tip: '江南慢活',
    tipClass: 'b-blue',
    b1: '♿ 無障礙',
    b1c: 'b-green',
    b2: '🌉 水鄉風情',
    b2c: 'b-blue',
    b3: '🍜 江南料理',
    b3c: 'b-orange'
  },
  {
    key: 'ne_9d_c',
    region: 'northeast',
    days: 9,
    name: '日韓精選東京首爾串聯 9天8夜',
    emoji: '✈️',
    c1: '#fbbf24',
    c2: '#f472b6',
    price: 52800,
    meta: '日本・韓國・小團10人・♿無障礙',
    tags: 'northeast accessible easy',
    tip: '日韓精選',
    tipClass: 'b-purple',
    b1: '♿ 無障礙',
    b1c: 'b-green',
    b2: '✈️ 雙城精選',
    b2c: 'b-purple',
    b3: '🍱 日韓美食',
    b3c: 'b-orange'
  },
  // 東北亞 11天 ×3
  {
    key: 'ne_11d_a',
    region: 'northeast',
    days: 11,
    name: '日韓中三國文化深度 11天10夜',
    emoji: '🌏',
    c1: '#818cf8',
    c2: '#fbbf24',
    price: 62800,
    meta: '日韓中三國・小團10人・♿無障礙',
    tags: 'northeast accessible',
    tip: '三國深度',
    tipClass: 'b-purple',
    b1: '♿ 無障礙',
    b1c: 'b-green',
    b2: '🌏 三國探索',
    b2c: 'b-purple',
    b3: '🏥 醫療保障',
    b3c: 'b-blue'
  },
  {
    key: 'ne_11d_b',
    region: 'northeast',
    days: 11,
    name: '中國絲路黃河文明探秘 11天10夜',
    emoji: '🏺',
    c1: '#fbbf24',
    c2: '#f97316',
    price: 52800,
    meta: '中國絲路黃河・小團10人・♿無障礙',
    tags: 'northeast accessible',
    tip: '文明探秘',
    tipClass: 'b-orange',
    b1: '♿ 無障礙',
    b1c: 'b-green',
    b2: '🏺 文明古蹟',
    b2c: 'b-orange',
    b3: '🚌 全程專車',
    b3c: 'b-blue'
  },
  {
    key: 'ne_11d_c',
    region: 'northeast',
    days: 11,
    name: '韓國蒙古草原雙主題 11天10夜',
    emoji: '🐎',
    c1: '#86efac',
    c2: '#a78bfa',
    price: 56800,
    meta: '韓國・蒙古・小團8人・♿無障礙',
    tags: 'northeast accessible',
    tip: '草原文化',
    tipClass: 'b-orange',
    b1: '♿ 無障礙',
    b1c: 'b-green',
    b2: '🐎 草原體驗',
    b2c: 'b-orange',
    b3: '⛺ 蒙古包住宿',
    b3c: 'b-teal'
  },
  // 東北亞 14天 ×3
  {
    key: 'ne_14d_a',
    region: 'northeast',
    days: 14,
    name: '東北亞四國深度文化慢旅 14天13夜',
    emoji: '🌏',
    c1: '#a78bfa',
    c2: '#fbbf24',
    price: 72800,
    meta: '東北亞四國・小團8人・♿無障礙',
    tags: 'northeast accessible',
    tip: '四國慢旅',
    tipClass: 'b-purple',
    b1: '♿ 無障礙',
    b1c: 'b-green',
    b2: '🌏 深度探索',
    b2c: 'b-purple',
    b3: '🏥 醫療保障',
    b3c: 'b-blue'
  },
  {
    key: 'ne_14d_b',
    region: 'northeast',
    days: 14,
    name: '中國全境南北絲路黃河長城 14天13夜',
    emoji: '🏯',
    c1: '#fca5a5',
    c2: '#818cf8',
    price: 65800,
    meta: '中國全境・小團10人・♿無障礙',
    tags: 'northeast accessible',
    tip: '中國全境',
    tipClass: 'b-orange',
    b1: '♿ 無障礙',
    b1c: 'b-green',
    b2: '🏯 文化全覽',
    b2c: 'b-orange',
    b3: '🚌 全程專車',
    b3c: 'b-blue'
  },
  {
    key: 'ne_14d_c',
    region: 'northeast',
    days: 14,
    name: '日本韓國蒙古三國精選 14天13夜',
    emoji: '🌏',
    c1: '#fbbf24',
    c2: '#4ade80',
    price: 68800,
    meta: '日韓蒙三國・小團8人・♿無障礙',
    tags: 'northeast accessible',
    tip: '三國精選',
    tipClass: 'b-purple',
    b1: '♿ 無障礙',
    b1c: 'b-green',
    b2: '🌏 三國文化',
    b2c: 'b-purple',
    b3: '🏥 醫療保障',
    b3c: 'b-blue'
  },
  // 10天 ×3
  {
    key: 'ne_10d_a',
    region: 'northeast',
    days: 10,
    name: '東北亞三國日韓中精選 10天9夜',
    emoji: '🌏',
    c1: '#818cf8',
    c2: '#fbbf24',
    price: 58800,
    meta: '日韓中三國・小團10人・♿無障礙',
    tags: 'northeast accessible',
    tip: '三國精選',
    tipClass: 'b-purple',
    b1: '♿ 無障礙',
    b1c: 'b-green',
    b2: '🌏 三國探索',
    b2c: 'b-purple',
    b3: '🏥 醫療保障',
    b3c: 'b-blue'
  },
  {
    key: 'ne_10d_b',
    region: 'northeast',
    days: 10,
    name: '中國絲路敦煌甘肅古道 10天9夜',
    emoji: '🏺',
    c1: '#fbbf24',
    c2: '#f97316',
    price: 48800,
    meta: '中國絲路・小團10人・♿無障礙',
    tags: 'northeast accessible',
    tip: '絲路探秘',
    tipClass: 'b-orange',
    b1: '♿ 無障礙',
    b1c: 'b-green',
    b2: '🏺 絲路文化',
    b2c: 'b-orange',
    b3: '🚌 全程專車',
    b3c: 'b-blue'
  },
  {
    key: 'ne_10d_c',
    region: 'northeast',
    days: 10,
    name: '韓國深度文化美食全覽 10天9夜',
    emoji: '🏯',
    c1: '#fca5a5',
    c2: '#818cf8',
    price: 52800,
    meta: '韓國全境・小團10人・♿無障礙',
    tags: 'northeast easy accessible',
    tip: '韓國深度',
    tipClass: 'b-purple',
    b1: '♿ 無障礙',
    b1c: 'b-green',
    b2: '🏯 文化深度',
    b2c: 'b-purple',
    b3: '🍜 韓食全覽',
    b3c: 'b-orange'
  },
  // 12天 ×3
  {
    key: 'ne_12d_a',
    region: 'northeast',
    days: 12,
    name: '東北亞文化深度全覽 12天11夜',
    emoji: '🌏',
    c1: '#a78bfa',
    c2: '#f472b6',
    price: 68800,
    meta: '東北亞・小團10人・♿無障礙',
    tags: 'northeast accessible',
    tip: '全境深度',
    tipClass: 'b-purple',
    b1: '♿ 無障礙',
    b1c: 'b-green',
    b2: '🌏 深度探索',
    b2c: 'b-purple',
    b3: '🏥 醫療保障',
    b3c: 'b-blue'
  },
  {
    key: 'ne_12d_b',
    region: 'northeast',
    days: 12,
    name: '中國南北縱走精華 12天11夜',
    emoji: '🏯',
    c1: '#fca5a5',
    c2: '#fbbf24',
    price: 58800,
    meta: '中國南北・小團12人・♿無障礙',
    tags: 'northeast accessible',
    tip: '南北精選',
    tipClass: 'b-orange',
    b1: '♿ 無障礙',
    b1c: 'b-green',
    b2: '🏯 南北文化',
    b2c: 'b-orange',
    b3: '🚌 全程專車',
    b3c: 'b-blue'
  },
  {
    key: 'ne_12d_c',
    region: 'northeast',
    days: 12,
    name: '蒙古西伯利亞草原極地 12天11夜',
    emoji: '🐎',
    c1: '#bfdbfe',
    c2: '#86efac',
    price: 62800,
    meta: '蒙古・俄羅斯西伯利亞・小團8人・♿無障礙',
    tags: 'northeast accessible',
    tip: '草原極地',
    tipClass: 'b-blue',
    b1: '♿ 無障礙',
    b1c: 'b-green',
    b2: '🐎 草原文化',
    b2c: 'b-blue',
    b3: '❄️ 極地探秘',
    b3c: 'b-purple'
  }
];
